this.events = [
{
"date": "25 Sep 11",
"place_name": "Avalon",
"artiste (Name)": "Boy George with Marc Vedo",
"genre": "Soul; DJ",
"time": "2100",
"Price ": "",
"description": "Boy George is a British singer-songwriter who was part of the English New Romantic movement which emerged in the early 1980s. He helped give androgyny an international stage with the success of Culture Club during the 1980s. His music is often classified as blue-eyed soul, which is influenced by rhythm and blues and reggae. His 1990s and 2000s-era solo music has glam influences such as David Bowie and Iggy Pop. He also founded and was lead singer of Jesus Loves You during the period 1989–1992. Being involved in many activities (among them songwriting, DJing, writing books, designing clothes and photography), he has released music recordings in the last decade. Marc Vedo is a half Portuguese, half English international DJ/producer/promoter currently residing in the Southwest of England in the city of Bristol, famous for producing bands like Massive Attack, Portishead, and Roni Size. Global music publication DJ Magazine quoted him as being \"a rising force on the international DJ scene\", whilst Mixmag as 'the next Sasha' for his impeccable mixing technique and pin-up like image.",
"Website": "http://www.avalon.sg/tickets.html",
},
{
"date": "25 Sep 11",
"place_name": "Avalon",
"artiste (Name)": "Chemical Brothers",
"genre": "Electronic",
"time": "",
"Price ": "",
"description": "The Chemical Brothers are a British electronic music duo comprising Tom Rowlands and Ed Simons, who met at the University of Manchester, England in 1992. Initially they called themselves \"The Dust Brothers.\" They changed their name in 1995 given the preexisting American production duo \"The Dust Brothers,\" their burgeoning popularity and the threat of legal action from the originals. Thus, their first album as The Chemical Brothers was titled Exit Planet Dust.",
"Website": "http://www.avalon.sg/",
},
{
"date": "25 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "25 Sep 11",
"place_name": "Paddock Club Lifestyle Stage",
"artiste (Name)": "F1: Bollywood Express",
"genre": "Bollywood",
"time": "1735-1755",
"Price ": "refer to www.singaporegp.com",
"description": "From the celebrated producers of the sold-out production 'Merchants of Bollywood', now comes the sensational train-themed musical blockbuster BOLLYWOOD EXPRESS. Listen up for cult favourites like 'Chaiyya Chaiyya' and 'Jaiho' and groove with the sexy cast in a 45-minute song-and-dance affair. Hindi music fans, don't miss this hip showcase at the Esplanade Outdoor Theatre (Zone 4) on Friday and the Village stage (Zone 1) on Saturday.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Marina, Zone 1",
"artiste (Name)": "F1: Brian Olsen",
"genre": "Art & Music",
"time": "1600-1700",
"Price ": "refer to www.singaporegp.com",
"description": "Experience creativity in its most kinetic form with BRIAN OLSEN as he turns a blank canvas into art within a matter of minutes. With music setting the mood, Brian will recreate colourful portraits of famous personalities using up to six brushes at a time. Olsen's artistic genius and showmanship sees him sought after all over the world. Be inspired at the Marina stage (Zone 1) on all three days.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Marina, Zone 1",
"artiste (Name)": "F1: Brian Olsen",
"genre": "Art & Music",
"time": "1835-1945",
"Price ": "refer to www.singaporegp.com",
"description": "Experience creativity in its most kinetic form with BRIAN OLSEN as he turns a blank canvas into art within a matter of minutes. With music setting the mood, Brian will recreate colourful portraits of famous personalities using up to six brushes at a time. Olsen's artistic genius and showmanship sees him sought after all over the world. Be inspired at the Marina stage (Zone 1) on all three days.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Marina, Zone 1",
"artiste (Name)": "F1: Chhaya Dewan",
"genre": "Pop Acoustic",
"time": "1735-1835",
"Price ": "refer to www.singaporegp.com",
"description": "Born and raised in Montreal Canada, Chhaya started singing and performing at the age of 4. In her teenage years she trained in Classical, Jazz and Gospel. By 2002, she had already released an album for which she toured Canada, the US and Europe. Some of her major performances since then include Miss India Canada, a NBA pre-show performance, and the Toronto Jazz Festival.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Esplanade Park, Zone 4",
"artiste (Name)": "F1: Earth Collide",
"genre": "Acoustic Rock",
"time": "1735-1835",
"Price ": "refer to www.singaporegp.com",
"description": "For three years, Earth (Lead Vocalist, Guitarist) searched for musicians who shared her love of acoustic rock. She collided with Surasak Pumdontree (Guitarist, Backing Vocalist) and Chumnansin Pedrit (Percussionist, Drummer) and the fit was perfect. Since then, they have been travelling around Thailand and the region, entertaining with their unique acoustic take on modern and classic hits.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Esplanade Outdoor Theatre, Zone 4",
"artiste (Name)": "F1: Forbidden Broadway",
"genre": "Musical Comedy",
"time": "1835-1920",
"Price ": "refer to www.singaporegp.com",
"description": "Just for laughs, indulge in the satirical brilliance of New York's longest running off-Broadway musical comedy revue, FORBIDDEN BROADWAY. Parodying popular shows like 'The Phantom of the Opera', 'Les Misérables', 'Hairspray', and 'The Lion King' as well as famous personalities the likes of Elton John and Hugh Jackman, Forbidden Broadway promises to tease you at the Village Stage (Zone 1) on Friday and the Esplanade Outdoor Theatre (Zone 4) on Sunday.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Marina, Zone 1",
"artiste (Name)": "F1: Indigo",
"genre": "Samba, 60s, 70s,",
"time": "2200-2300",
"Price ": "refer to www.singaporegp.com",
"description": "Indigo is the first band outfit in Singapore to offer authentic Brazilian-samba styled music from the 60's, samba funk of the 70's as well as Brazilian electronica. INDIGO is all about the melodies and rhythms blending together to bring about a solid groove with the energy to get people moving.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Padang Main Stage, Zone 4",
"artiste (Name)": "F1: Linkin Park",
"genre": "Rock",
"time": "2230-2430",
"Price ": "refer to www.singaporegp.com",
"description": "LINKIN PARK’s live show is a transformative multi-media experience, with visual technology that befits the power of the music. The band was voted ‘Best Live Act’ at the 2010 MTV European Music Awards. The setlist will combine the biggest hits of the band’s career, as well as new material from A Thousand Suns.  With more acts to be announced, fans can look forward to a global sporting event that offers spectacular Formula One race action and the world’s best entertainment, all for the price of one ticket.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Village Area, Zone 1",
"artiste (Name)": "F1: Rick Astley",
"genre": "Retro Pop",
"time": "1830-1930",
"Price ": "refer to www.singaporegp.com",
"description": "Catch retro fever as legendary showman RICK ASTLEY belts out irresistible hits such as 'Together Forever' and 'Never Gonna Give You Up' at the Esplanade Outdoor Theatre (Zone 4) on Saturday and Village Stage (Zone 1) on Sunday. Having sold more than forty million albums worldwide, Astley holds the record for being the only male solo artist to have his first eight singles reach the Top 10 in the UK.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Village Area, Zone 1",
"artiste (Name)": "F1: Shaggy",
"genre": "Raggae Pop",
"time": "2210-2310",
"Price ": "refer to www.singaporegp.com",
"description": "With worldwide hits like 'Mr Boombastic', 'It Wasn't Me' and 'Angel', Grammy Award-winning singer-rapper SHAGGY is the biggest crossover success in reggae and pop. The multi-platinum artiste's unmistakably deep vocals and feel-good music will keep your mood high and the party going at the Esplanade Outdoor Theatre (Zone 4 – Saturday) and Village Stage (Zone 1 – Sunday).",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Village Area, Zone 1",
"artiste (Name)": "F1: Studio Festi",
"genre": "Italian Dance",
"time": "1735-1800",
"Price ": "refer to www.singaporegp.com",
"description": "After enchanting audiences at the 2010 Singapore Grand Prix with their magical world of stellar installations and breath-taking performance, Singapore GP is pleased to once again present two specially commissioned acts by the iconic Italian production maestro, Studio Festi, at the Marina Bay Street Circuit this year.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Padang Main Stage, Zone 4",
"artiste (Name)": "F1: Transe Express",
"genre": "Perscussion",
"time": "1900-1945",
"Price ": "refer to www.singaporegp.com",
"description": "Follow crowd gatherers TRANSE EXPRESS as they drum up a Pied Piper procession exclusive to Zone 4 on Saturday and Sunday. Watch a ravishing trapezist perform stunning feats in midair, accompanied by percussionists who are lifted 40 metres from the ground midway through their drumming routines. Like a gigantic child's mobile careering through the audience, this aerial performance is truly a sight to behold.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Paddock Club Lifestyle Stage",
"artiste (Name)": "F1: Vox",
"genre": "Acapella",
"time": "2200-2300",
"Price ": "refer to www.singaporegp.com",
"description": "VOX is made up of 4 talented individuals who are classically trained yet aims to give a new spin to the traditional classical setting.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "25 Sep 11",
"place_name": "Bay Floating Platfom- Zone 3",
"artiste (Name)": "F1: Zouk: Mambo Jumbo",
"genre": "80's hits",
"time": "1915-1945",
"Price ": "refer to www.singaporegp.com",
"description": "You know you want to relive the hits of your youth (or your parents' era!) so put on those dancing shoes and Mambo Jambo with us on Sunday night at the floating platform (Zone 3) – exclusive for Bay Grandstand ticketholders only. Celebrating its 20th anniversary, Zouk will lead a synchronised mass dance and spin a colourful mix of '80s hits and mainstream tunes. Get that party started already!",
"Website": "http://www.singaporegp.sg/",
},
{
"date": "25 Sep 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Jack & Rai",
"genre": "Pop rock",
"time": "-",
"Price ": "Free + F&B Charges",
"description": "The boys have been woing the crowd at Wala Wala for years. Sundays take on a different twist when they entertain with a cosy yet somewhat relaxed night of acoustic pop tunes and their originals",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "25 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Jam Session",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "25 Sep 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "25 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "25 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Timbre Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "25 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Victor Tang",
"genre": "Acoustic; Top 40's",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "26 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "26 Sep 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "26 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "26 Sep 11",
"place_name": "New Asia Bar",
"artiste (Name)": "DJ Miss Roxx",
"genre": "",
"time": "2200",
"Price ": "$25++",
"description": "Recently elected as one of the 100 most beautiful Playboy Playmates, DJane Miss ROXX has been hitting hard at clubs across Europe, Tunisia, Morocco, Brazil, Monaco and Russia. Her bass-lifting music, a deeply-touching mix of electro-house and progressive techno, is guaranteed to tear the walls down, fill the dance floor, and keep New Asia slamming until the morning light. On this night, DJ Miss ROXX will finish the Night Race weekend in style—as the lights around the race track die away, her light will continue to shine on throughout the night, pumping out looping rhythms that will carry partygoers to ecstasy.",
"Website": "http://www.singaporegp.sg/media/entertainment_2011.php",
},
{
"date": "26 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "26 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Sep 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Pam & Chris",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Sep 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Surath & Rene",
"genre": "Pop Rock",
"time": "2030-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Wanyue",
"genre": "Chinese; Pop",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "26 Sep 11",
"place_name": "Balaclava",
"artiste (Name)": "Wendy & David",
"genre": "classic; jazz",
"time": "2000",
"Price ": "Free + F&B Charges",
"description": "The dynamic duo accompany guests down memory lane with ther selection of evergreen classics and the occasional jazz number. Soulful yet intriguing, Wendy's singing is an enchantment to be remembered by many",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "27 Sep 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Sep 11",
"place_name": "Esplanade Recital Studio",
"artiste (Name)": "Asian Jazz All-Stars Power Quartet",
"genre": "Jazz",
"time": "1930",
"Price ": "$42",
"description": "Known as The Asian Jazz All-Stars Power Quartet, the band comprises Singapore’s own ‘King of Swing’ jazz pianist/organ maestro Jeremy Monteiro; Eugene Pao, arguably Asia’s top jazz guitarist from Hong Kong; Tots Tolentino, saxophone extraordinaire from Philippines; and Hong Chanutr Techatana-nan, one of the most innovative and exciting drummers to emerge in the Asian jazz scene, from Thailand. This powerful amalgamation of Asian jazz leaders is bound to create musical alchemy for their shows taking place in the intimate setting of Esplanade Recital Studio.",
"Website": "none",
},
{
"date": "27 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "27 Sep 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "27 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "27 Sep 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Sep 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "27 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "27 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Singapore Char Siew Bao",
"genre": "Acoustic; Top 40's",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "27 Sep 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "This electrifying 4 piece dish out a repertoire of classic rock hits alongside top 40's favourites. Expect to hear songs by U2, The Killers, Greenday and just about any band you can think of",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "27 Sep 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Unified",
"genre": "Top 40's; Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "28 Sep 11",
"place_name": "Esplanade Recital Studio",
"artiste (Name)": "Asian Jazz All-Stars Power Quartet",
"genre": "Jazz",
"time": "1930",
"Price ": "$42",
"description": "Known as The Asian Jazz All-Stars Power Quartet, the band comprises Singapore’s own ‘King of Swing’ jazz pianist/organ maestro Jeremy Monteiro; Eugene Pao, arguably Asia’s top jazz guitarist from Hong Kong; Tots Tolentino, saxophone extraordinaire from Philippines; and Hong Chanutr Techatana-nan, one of the most innovative and exciting drummers to emerge in the Asian jazz scene, from Thailand. This powerful amalgamation of Asian jazz leaders is bound to create musical alchemy for their shows taking place in the intimate setting of Esplanade Recital Studio.",
"Website": "http://www.esplanade.com/whats_on/programme_info/the_asian_jazz_all-stars_power_...",
},
{
"date": "28 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "28 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "28 Sep 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Sep 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "28 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "28 Sep 11",
"place_name": "Quarubar",
"artiste (Name)": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "28 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Ling Kai and Selena",
"genre": "Acoustic; Top 40's; Rock",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "28 Sep 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Sep 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "28 Sep 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "Ngak is no stranger to the local pop scene as he can be seen doing Mandarin numbers on television. At Wala Wala, he moves the crowd with a delectable choice of current English hits, as well as yesteryears' pop favorites.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "29 Sep 11",
"place_name": "Timbre Old School",
"artiste (Name)": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "29 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "29 Sep 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "29 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Howie and Nelson",
"genre": "Rock; Top 40's; English; Chinese",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "29 Sep 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "29 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "29 Sep 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "No strangers to our music scene. Since April 2002, they have been regular perfomers at Wala Wala and Balaclava. Shirlyn, lead singer and guitarist, has a solo album under her belt while the other members are respected musicians in their own rights. Musically, they are pretty much up for anything and everything. Theri repertoire ranges from anything pop to hard rock.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "29 Sep 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "The Common People",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Sep 11",
"place_name": "Quarubar",
"artiste (Name)": "Wayne Sandz & Wayne Gideon",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "30 Sep 11",
"place_name": "Timbre Substation",
"artiste (Name)": "53A",
"genre": "Pop",
"time": "2230-0145",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "30 Sep 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "30 Sep 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "30 Sep 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Energy",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "30 Sep 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Enigma",
"genre": "Top 40's",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "30 Sep 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "30 Sep 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "30 Sep 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "30 Sep 11",
"place_name": "Quarubar",
"artiste (Name)": "Michaela Therese & Joe Jayaveeran",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "30 Sep 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Ngak and the Timmy! Band",
"genre": "Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "30 Sep 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "30 Sep 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "The Common People",
"genre": "Pop rock",
"time": "-",
"Price ": "Free + F&B Charges",
"description": "This outfit of 5 has grown to be known as the party band of Wala Wala! With their thirst to provide the best of yesterday's and today's songs, they have become the band to watch along Holland Village on Friday nights.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "1 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Alemay & Shawn Letts",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "1 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "1 Oct 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Energy",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "1 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Enigma",
"genre": "Top 40's",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "1 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "1 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "In Each Hand A Cutlass",
"genre": "",
"time": "2030-2115",
"Price ": "Free + F&B Charges",
"description": "http://www.facebook.com/IEHAC",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "1 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "1 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Pennylane Band",
"genre": "Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "1 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "No strangers to our music scene. Since April 2002, they have been regular perfomers at Wala Wala and Balaclava. Shirlyn, lead singer and guitarist, has a solo album under her belt while the other members are respected musicians in their own rights. Musically, they are pretty much up for anything and everything. Theri repertoire ranges from anything pop to hard rock.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "1 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Sofia & Fatt",
"genre": "Pop Rock",
"time": "2115-1230",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "1 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "The Common People",
"genre": "Pop Rock",
"time": "2130-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "2 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Bushman",
"genre": "Raggae",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "2 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "2 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Jack & Rai",
"genre": "Pop rock",
"time": "-",
"Price ": "Free + F&B Charges",
"description": "The boys have been woing the crowd at Wala Wala for years. Sundays take on a different twist when they entertain with a cosy yet somewhat relaxed night of acoustic pop tunes and their originals",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "2 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Jam Session",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "2 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "2 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "2 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Timbre Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "2 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Victor Tang",
"genre": "Acoustic; Top 40's",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "3 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "3 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "3 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "3 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "3 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "3 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Pam & Chris",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "3 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Surath & Rene",
"genre": "Pop Rock",
"time": "2030-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "3 Oct 11",
"place_name": "Esplanade Recital Studio",
"artiste (Name)": "Tandy Lim: Songs of Liu San Jie",
"genre": "Chinese; folk",
"time": "1030, 1500",
"Price ": "$12",
"description": "Liu San-Jie (Third Sister Liu) is a classic Chinese movie filmed in 1960 about a talented singer of folk songs. Besides the scenic Guilin landscape, the songs in the film are still remembered by many till this day. Relive the story as versatile local songstress and vocal trainer Tandy Lim brings you a selection of songs from Liu San-Jie.",
"Website": "http://www.esplanade.com/whats_on/programme_info/songs_of_liu_san-jie/index.jsp",
},
{
"date": "3 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Wanyue",
"genre": "Chinese; Pop",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "3 Oct 11",
"place_name": "Balaclava",
"artiste (Name)": "Wendy & David",
"genre": "classic; jazz",
"time": "2000",
"Price ": "Free + F&B Charges",
"description": "The dynamic duo accompany guests down memory lane with ther selection of evergreen classics and the occasional jazz number. Soulful yet intriguing, Wendy's singing is an enchantment to be remembered by many",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "3 Oct 11",
"place_name": "Singapore Indoor Stadium",
"artiste (Name)": "Westlife",
"genre": "Pop",
"time": "2000",
"Price ": "$80-$150",
"description": "The quartet’s eleventh offering, Gravity, sees the Irishmen sail into uncharted waters, wrestle an unprecedented level of creative control and most critically of all – start believing in themselves again. “It’s a really good album,” insists Nicky Byrne. “It’s one producer. It’s one sound. Maybe it’s taken us twelve years to get there. But it doesn’t matter. We’re here now.  “It’s the kind of record we knew we could make and we just needed the right person to deliver it with us.”  And that individual was legendary producer John Shanks. He steered Take That’s last two collections, was responsible for Bon Jovi’s recent reinvention and sculpted some of Kelly Clarkson, Celine Dion and Sheryl Crow’s most enduring hits.",
"Website": "http://www.midaspromotions.com/upcoming.htm",
},
{
"date": "4 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "4 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "4 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "4 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "4 Oct 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Enigma",
"genre": "Top 40's",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "4 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "4 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "4 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "4 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "4 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Neh'mind- Tribute to Nirvana's Nevermind",
"genre": "Pop; Rock",
"time": "1900",
"Price ": "Free + F&B Charges",
"description": "Event titled Neh’mind, five Singapore artists/bands - Fatskunks, Goodfellas, Lunarin, Michaela Therese and The Lard Brothers are invited to play tribute to the iconic Nevermind album in their own unique ways (think of this like SPIN’s tribute Newermind but live on stage). Neh’mind is not just a night with musicians covering classic songs from Nevermind, Nirvana-style but a night for artists to dice, slice, dissect and present their own unique interpretation of the songs. Perhaps “Smells Like Teen Spirit” reggae style? “Come As You Are” in jazz tones? This event also highlights the enormous influence Nirvana has on our Singapore musicians and songwriters lyrically, musically and philosophically, and to celebrate that, the featured artists will also be performing one of their own originals to showcase their personalities on stage.",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "4 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Singapore Char Siew Bao",
"genre": "Acoustic; Top 40's",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "4 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "This electrifying 4 piece dish out a repertoire of classic rock hits alongside top 40's favourites. Expect to hear songs by U2, The Killers, Greenday and just about any band you can think of",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "4 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "5 Oct 11",
"place_name": "The Coliseum, Hard Rock Hotel Singapore",
"artiste (Name)": "Alice Cooper",
"genre": "Hard Rock",
"time": "1900",
"Price ": "$120",
"description": "This will be Alice Cooper’s inaugural show in Singapore and we are in for quite a treat. As an artist, he has both been influenced by and then influenced horror movies and garage rock to pioneer a spectacular theatrical brand of hard rock that was designed to shock and Alice Cooper is the master of the genre. His fans range from Salvador Dali to Bob Dylan to Foo Fighters – Dave Grohl and Johnny Depp, who took the stage with Alice Cooper and his Band at the legendary “100 Club” in London last month. Without Alice Cooper the world would never have seen Bands like the New York Dolls, Kiss, Marilyn Manson, Nine Inch Nails, Motley Crue, Slipnot or Rob Zombie, all of whom have been considerably influenced by the legendary Alice Cooper.",
"Website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=alice1011",
},
{
"date": "5 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "5 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "5 Oct 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Energy",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "5 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "5 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "5 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "5 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "5 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Ling Kai and Selena",
"genre": "Acoustic; Top 40's; Rock",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "5 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "5 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "5 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "5 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "Ngak is no stranger to the local pop scene as he can be seen doing Mandarin numbers on television. At Wala Wala, he moves the crowd with a delectable choice of current English hits, as well as yesteryears' pop favorites.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "6 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "6 Oct 11",
"place_name": "Wave House Sentosa",
"artiste (Name)": "All Time Low & The Dirt Radicals",
"genre": "Pop Punk; Rock",
"time": "2000",
"Price ": "$68",
"description": "Fans of pop-punk, wait no more! Come this October 6th, American band All Time Low will bring their infectious tunes and energetic stage performance to Singapore! With their radio-friendly tunes and tongue-in-cheek lyrics, it is no wonder that the band earned the reputation of being one of pop-punk’s hottest new bands and is well on their way to world domination.  Following the success of their third album, Nothing Personal, the band did not disappoint and instead, went on to create more chart-topping hits. Their latest record, DIRTY WORK, debut on Billboard Top 200 chart at #6 and held the #1 spot on the iTunes album chart for three consecutive days and is now blazing up airwaves all over.",
"Website": "http://www.sistic.com.sg/portal/dt?retry=1&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&contentCode=low1011&dt.isPortletRequest=true&dt.provider=PortletWindowProcessChannel&dt.containerName=JSPTabContainer/sEventsCalendar&dt.action=process&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER",
},
{
"date": "6 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "6 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "6 Oct 11",
"place_name": "The Substation",
"artiste (Name)": "Every Time I Die & The Acacia Strain double bill",
"genre": "Rock; Metalcore",
"time": "1900",
"Price ": "$80 (Early bird)/$100",
"description": "Every Time I Die is a metalcore band from Buffalo, New York, formed in 1998.Their musical style, while rooted in technical hardcore variously displays strong southern metal and mathcore influences, and is also characterised by their cryptic, bitingly sarcastic lyrics. The band announced on July 14, 2008 that they had left Ferret Music and signed with Epitaph.Their fifth album, New Junk Aesthetic, was released on September 15, 2009.  The Acacia Strain is an American band from Chicopee, Massachusetts. Originally founded in 2001, the band itself has undergone numerous changes in the member line-up. To date they have released five studio albums, as well as two split albums: one with Loyal to the Grave (on which they covered the Slayer song \"Seasons in the Abyss\") and another with This or the Apocalypse, War from a Harlots Mouth, Fact, and Aggressive Dogs. The band has worked with acclaimed producers Adam Dutkiewicz and Chris \"Zeuss\" Harris.",
"Website": "http://www.facebook.com/people/Bone-Crusher/100000599947607",
},
{
"date": "6 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "6 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Howie and Nelson",
"genre": "Rock; Top 40's; English; Chinese",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "6 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "6 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "No strangers to our music scene. Since April 2002, they have been regular perfomers at Wala Wala and Balaclava. Shirlyn, lead singer and guitarist, has a solo album under her belt while the other members are respected musicians in their own rights. Musically, they are pretty much up for anything and everything. Theri repertoire ranges from anything pop to hard rock.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "6 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "The Common People",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "6 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Wayne Sandz & Wayne Gideon",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "7 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "53A",
"genre": "Pop",
"time": "2230-0145",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "7 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "7 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "7 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Energy",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "7 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "7 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "7 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "7 Oct 11",
"place_name": "Singapore Indoor Stadium",
"artiste (Name)": "Loud Festival: Jay Chou, Landy Wen, Cindy Yen, Sodagreen, Qing Feng",
"genre": "Chinese; Pop",
"time": "2000",
"Price ": "$88-$198",
"description": "“LOUD Festival”, featuring Asia’s King of Mando-Pop Jay Chou, award winning popular band Sodagreen, sultry karaoke favourite Landy Wen, and gifted newcomer Cindy Yen, is a two hours music extravaganza that will be held at the Singapore Indoor Stadium on 7th October 2011.  Headlined by Jay Chou, the multi-talented Taiwanese singer will serenade with his ballads and R&B tunes accompanied by his solo performances on the piano and guitar. The high-spirited Sodagreen is all set to charm with the lead singer, Qing Feng’s electrifying vocals and witty stage persona. “Dancing Queen”, Landy Wen, will bring the house to their feet as she wows with her dance medleys and nifty moves, as well as her karaoke friendly hits. Sassy newcomer, Cindy Yen, will be the special guest for this concert.",
"Website": "http://www.unusual.com.sg",
},
{
"date": "7 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Michaela Therese & Joe Jayaveeran",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "7 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Ngak and the Timmy! Band",
"genre": "Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "7 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "7 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "The Common People",
"genre": "Pop rock",
"time": "-",
"Price ": "Free + F&B Charges",
"description": "This outfit of 5 has grown to be known as the party band of Wala Wala! With their thirst to provide the best of yesterday's and today's songs, they have become the band to watch along Holland Village on Friday nights.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "8 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Alemay & Shawn Letts",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "8 Oct 11",
"place_name": "Alliance Franxaise Theatre",
"artiste (Name)": "Cedruc Hanriot",
"genre": "Jazz",
"time": "2000-2200",
"Price ": "$35",
"description": "",
"Website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=groove1011",
},
{
"date": "8 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "8 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "8 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Enigma",
"genre": "Top 40's",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "8 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "8 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "8 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "8 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Pennylane Band",
"genre": "Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "8 Oct 11",
"place_name": "Fort Canning Park",
"artiste (Name)": "Retrolicious: Belinda Carlisle, Bananaram, Human League",
"genre": "Retro",
"time": "2000",
"Price ": "$105, $195, Child: $50",
"description": "Singapore’s biggest outdoor retro concert festival has upped its ante to bring you even bigger and better music acts. Nominated by I-S Magazine as “Concert of the Year 2010”, RETROLICIOUS™ 2011 is all geared up to lead the 80’s reprisal so let’s rock together at Fort Canning Park and party like it's 1989! Presented by Running Into The Sun and Class 95FM, 80’s phenomenal pop icons BELINDA CARLISLE, female duo BANANARAMA and THE HUMAN LEAGUE will be in Singapore to take on centre-stage. More than simply a ‘live’ concert, RETROLICIOUS™ is your official 80’s “Heaven is a Place on Earth” wonderland that presents the other well-loved facets of the 80’s era, this year, it will be in the form of The Retro Village. Coupled with amazing music, this retro village hosts an array of festival activity so come early and picnic with your fellow music lovers. Not forgetting the signature fashion trends inspired from the 80’s, RETROLICIOUS™ is also set to be an occasion for all to celebrate everyone’s favourite style looks of the 80’s! Dress the part by donning those infamous shoulder pads, mega hoop earrings, neon leggings, oversized tees, with a dose of your own interpretation.",
"Website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=retro1011",
},
{
"date": "8 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "SCIM #23 (Sound, La’dies, Hybrid, Phaze)",
"genre": "",
"time": "1900-2130",
"Price ": "Free + F&B Charges",
"description": "http://www.facebook.com/IEHAC#!/event.php?eid=119648018135270",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "8 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "No strangers to our music scene. Since April 2002, they have been regular perfomers at Wala Wala and Balaclava. Shirlyn, lead singer and guitarist, has a solo album under her belt while the other members are respected musicians in their own rights. Musically, they are pretty much up for anything and everything. Theri repertoire ranges from anything pop to hard rock.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "8 Oct 11",
"place_name": "Timbre Old School",
"artiste (Name)": "Sofia & Fatt",
"genre": "Pop Rock",
"time": "2115-1230",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "8 Oct 11",
"place_name": "Timbre Arts House",
"artiste (Name)": "The Common People",
"genre": "Pop Rock",
"time": "2130-0045",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "9 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "9 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Jack & Rai",
"genre": "Pop rock",
"time": "-",
"Price ": "Free + F&B Charges",
"description": "The boys have been woing the crowd at Wala Wala for years. Sundays take on a different twist when they entertain with a cosy yet somewhat relaxed night of acoustic pop tunes and their originals",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "9 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Jam Session",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "9 Oct 11",
"place_name": "The Pump Room @ Clarke Quay",
"artiste (Name)": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"Price ": "Free + F&B Charges",
"description": "The inimitable Jive Talkin' spices up the evening with its vibrant and funky repertoire of top 40s, pop, rock and jazz. Dance till you drop!",
"Website": "http://www.pumproomasia.com/home.html",
},
{
"date": "9 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "9 Oct 11",
"place_name": "Timbre Substation",
"artiste (Name)": "Timbre Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "9 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Victor Tang",
"genre": "Acoustic; Top 40's",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "10 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "10 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "10 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "10 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "10 Oct 11",
"place_name": "Balaclava",
"artiste (Name)": "Wendy & David",
"genre": "classic; jazz",
"time": "2000",
"Price ": "Free + F&B Charges",
"description": "The dynamic duo accompany guests down memory lane with ther selection of evergreen classics and the occasional jazz number. Soulful yet intriguing, Wendy's singing is an enchantment to be remembered by many",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "11 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "11 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "11 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "11 Oct 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Enigma",
"genre": "Top 40's",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "11 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "11 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "This electrifying 4 piece dish out a repertoire of classic rock hits alongside top 40's favourites. Expect to hear songs by U2, The Killers, Greenday and just about any band you can think of",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "11 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "12 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "12 Oct 11",
"place_name": "Highlander",
"artiste (Name)": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.highlanderasia.com/",
},
{
"date": "12 Oct 11",
"place_name": "Hard Rock Café Sentosa",
"artiste (Name)": "Energy",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "12 Oct 11",
"place_name": "Yello Jello Retrobar",
"artiste (Name)": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "It's hard to choose which fact is more surprising. That home-grown singer John Molina has been entertaining loyal fans for more than 15 years now or that John He's-still-so-hot! Is still only in his mid 30s. John's storied career started in 1993 and has seen him resident and guest at Singapore's leading live band venues as well as all around the region. It is hard to identify which club he is most associated with, as fans gladly follow him from place to place. Check him out at Yello Jello!",
"Website": "http://www.yellojello.sg/",
},
{
"date": "12 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "12 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "12 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "Ngak is no stranger to the local pop scene as he can be seen doing Mandarin numbers on television. At Wala Wala, he moves the crowd with a delectable choice of current English hits, as well as yesteryears' pop favorites.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "13 Oct 11",
"place_name": "Crazy Elephant",
"artiste (Name)": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.crazyelephant.com/",
},
{
"date": "13 Oct 11",
"place_name": "Hard Rock Café",
"artiste (Name)": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"Price ": "Free + F&B Charges",
"description": "",
"Website": "http://www.hardrock.com",
},
{
"date": "13 Oct 11",
"place_name": "Wala Wala Café Bar",
"artiste (Name)": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"Price ": "Free + F&B Charges",
"description": "No strangers to our music scene. Since April 2002, they have been regular perfomers at Wala Wala and Balaclava. Shirlyn, lead singer and guitarist, has a solo album under her belt while the other members are respected musicians in their own rights. Musically, they are pretty much up for anything and everything. Theri repertoire ranges from anything pop to hard rock.",
"Website": "http://www.imaginings.com.sg/",
},
{
"date": "13 Oct 11",
"place_name": "Quarubar",
"artiste (Name)": "Wayne Sandz & Wayne Gideon",
"genre": "Jazz; Latin; Tango",
"time": "",
"Price ": "Free + F&B Charges",
"description": "Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.",
"Website": "http://www.facebook.com/group.php?gid=46581108311",
},
{
"date": "15 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Cockpit",
"genre": "",
"time": "2030-2115",
"Price ": "Free + F&B Charges",
"description": "http://www.facebook.com/wearecockpit",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "22 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Manhand (Malayisa HipHop band)",
"genre": "Hip Hop",
"time": "",
"Price ": "Free + F&B Charges",
"description": "http://www.facebook.com/manhand.music",
"Website": "http://www.hoodbarandcafe.com/",
},
{
"date": "29 Oct 11",
"place_name": "Hood Bar & Café",
"artiste (Name)": "Opposition Party",
"genre": "",
"time": "",
"Price ": "Free + F&B Charges",
"description": "http://www.oppositionparty.net/",
"Website": "http://www.hoodbarandcafe.com/",
},
]
