this.places = [
"Acid Bar": {
"address": "180 Orchard Road, Peranakan Place",
"postal": "238846",
"tel": "6738 8828",
"details": "Aptly described as an enclave with edge and soul by grungy barflies and creative cracks. Experience a blend of sensory elements and take flight to a different plane. Acoustic sessions featuring genres of radio alternatives, top 40s and an occasional touch of percussions are played nightly from 7pm.  Consume nightly before rest a myriad of concoctions; tray of 25 apple/lychee shooters and buckets of the golden juice with touch go budgets.  Fret not growling guts as our kitchen maestro whips up tantelicious hot chicken wings and crunchy calamari while acid bar croons and the blue cows dance.",
},
"Blujaz Cafe": {
"address": "11 Bali Lane",
"postal": "189848",
"tel": "6292 3800",
"details": "At BluJaz, we believe in the simple things of life. Simple things that have somehow become so hard to find. Good food. Love. Laughter. Friends. Family. Music. Conversation. And decent prices, because no one should be allowed to pay fifty dollars for a meal.",
},
"Brix": {
"address": "10 Scotts Rd, Basement, Grand Hyatt Singapore",
"postal": "228211",
"tel": "6732-1234",
"details": "There’s a lively yet sophisticated feel to Brix, buried in the basement of the Grand Hyatt Regency. Despite its subterranean location, it’s not at all dingy, and crowds flock here to enjoy the live music from the popular house band. International bands occasionally perform too. Divided in two, a Music Bar, where the band play a pleasing blend of jazz and R&B, and a Wine & Whiskey Bar, which, good to its name, serves up a fine selection of wine, Scotch, and cognac. It can get quite lively on the weekend, the blend of music, dancing and decent drinks, unsurprisingly proving alluring, so dress to impress to ensure you get in. Reservations are also recommended on busy nights.",
},
"China One": {
"address": "Block 3E River Valley Road #02-01 Clarke Quay",
"postal": "179024",
"tel": "6339 0280",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Crazy Elephant": {
"address": "Clarke Quay, 3E River Valley Road, #01-03/04",
"postal": "179024",
"tel": "6337 7859",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Esplanade Concert Hall": {
"address": "1 Esplanade Drive",
"postal": "38981",
"tel": "8288377",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Highlander": {
"address": "Block 3B The Foundry #01-11 Clarke Quay River Valley Road",
"postal": "179021",
"tel": "6235 9528",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Hood": {
"address": "55 Keong Saik Road",
"postal": "89158",
"tel": "62218846",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Quarubar": {
"address": "113 Frankel Ave",
"postal": "458230",
"tel": "6243 0113",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Timbre Arts House": {
"address": "1 Old Parliament Lane",
"postal": "179429",
"tel": "6332 6900",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Timbre Old School": {
"address": "11A Mount Sophia",
"postal": "179936",
"tel": "6338 8277",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Timbre Substation": {
"address": "45 Armenian Street",
"postal": "179936",
"tel": "6338 8277",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Wala Wala": {
"address": "31 Lorong Mambong Holland Village",
"postal": "277689",
"tel": "64624288",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
"Yello Jello Retrobar": {
"address": "Clarke Quay, Blk 3C The Cannery, River Valley Rd, #01-06",
"postal": "179021",
"tel": "6887 3733",
"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
},
]
