this.events = [
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Acid Bar",
"artiste": "Nelson",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Acid Bar",
"artiste": "Tuna Pop",
"genre": "Acoustic",
"time": "2130-0045",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Blujaz Cafe",
"artiste": "Greg Lyons and 10 piece band, Omniform",
"genre": "Jazz",
"time": "2130",
"price": "$$ *Free entry",
"description": "What started off as a chance to play Greg’s arrangements has evolved to include all the individual characters that form the band. The repertoire is still made up largely of Greg’s compositions and wholly of his arrangements which draw from just about every genre of music. Omniform also features some awesome and very individual soloists. Monster Trio, sometimes a quartet consists of talented musicians.",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "China One",
"artiste": "Tonelab",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Esplanade Concert Hall",
"artiste": "The 50s Rock & Roll",
"genre": "Rock",
"time": "1030; 1500",
"price": "$10-12",
"description": "Enjoy and rock to the music of the 50s including Johnny Be Good, Rock Around the Clock, Great Balls of Fire, Hound Dog, La Bamba and more, performed by home grown band Jerry N The Neu Faces!",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Hood",
"artiste": "Wanyue",
"genre": "Pop",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Quarubar",
"artiste": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Timbre Arts House",
"artiste": "Surath & Rene",
"genre": "Jazz",
"time": "2030-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Timbre Old School",
"artiste": "Pam & Chris",
"genre": "Jazz",
"time": "1945-2300",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Timbre Substation",
"artiste": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Wala Wala",
"artiste": "Three",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/4/2011",
"day": "Monday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Acid Bar",
"artiste": "Joshua Alexis",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Acid Bar",
"artiste": "Kulture",
"genre": "Acoustic",
"time": "2130-0045",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "Free (excl F&B)",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "China One",
"artiste": "Lydia Low and DJ Tovan",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Hood",
"artiste": "Singapore Char Siew Bao",
"genre": "",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Quarubar",
"artiste": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Timbre Arts House",
"artiste": "53A",
"genre": "Rock",
"time": "2015-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Timbre Old School",
"artiste": "Fatt, Shili & Adi",
"genre": "Rock",
"time": "1945-2300",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Timbre Substation",
"artiste": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Wala Wala",
"artiste": "Hush",
"genre": "Pop Rock",
"time": "1900",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Wala Wala",
"artiste": "Tabula",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/5/2011",
"day": "Tuesday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Acid Bar",
"artiste": "Jamiel",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Acid Bar",
"artiste": "Pam & Fatt",
"genre": "Acoustic",
"time": "2130-0045",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "China One",
"artiste": "Inertia (Acoustic) & DJ Tovan",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Hood",
"artiste": "Shimona",
"genre": "",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Quarubar",
"artiste": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Timbre Arts House",
"artiste": "Enigma",
"genre": "Rock",
"time": "2015-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Timbre Old School",
"artiste": "Liza & Joey",
"genre": "Rock",
"time": "1945-2300",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Timbre Substation",
"artiste": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Wala Wala",
"artiste": "Ngak",
"genre": "Pop Rock",
"time": "1900",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Wala Wala",
"artiste": "Timmy",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/6/2011",
"day": "Wednesday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Acid Bar",
"artiste": "Nelson",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Acid Bar",
"artiste": "Tuna Pop",
"genre": "Acoustic",
"time": "2130-0045",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "China One",
"artiste": "Tabula (Acoustic) & DJ Tovan",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Hood",
"artiste": "Howie + Nelson",
"genre": "",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Quarubar",
"artiste": "Wayne Sandz & Joe",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Timbre Arts House",
"artiste": "Iris Feat. Liza",
"genre": "Rock",
"time": "2015-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Timbre Old School",
"artiste": "53A",
"genre": "Rock",
"time": "2015-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Timbre Substation",
"artiste": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Wala Wala",
"artiste": "Victor Tang",
"genre": "Pop Rock",
"time": "1900",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Wala Wala",
"artiste": "The Unexpected",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/7/2011",
"day": "Thursday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Acid Bar",
"artiste": "Matt",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Acid Bar",
"artiste": "Sofia & Fatt",
"genre": "Acoustic",
"time": "2130-0015",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Acid Bar",
"artiste": "Sugarlove",
"genre": "Acoustic",
"time": "0030-0215",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "China One",
"artiste": "Tabula (Full Band) and DJ Tovan",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Esplanade Concert Hall",
"artiste": "Presidents Young Performers Concert",
"genre": "Classical",
"time": "1930",
"price": "$15*, $22*, $32*, $42, $58, $72 Concessions: Concessions for students, NSF and senior citizens: 30% savings",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Hood",
"artiste": "Timmy! Band",
"genre": "",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Quarubar",
"artiste": "Carlos",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Timbre Arts House",
"artiste": "Goodfellas",
"genre": "Pop",
"time": "2130-1245",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Timbre Old School",
"artiste": "Alicia Pan & Adrian",
"genre": "Pop",
"time": "2015-2330",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Timbre Substation",
"artiste": "53A",
"genre": "Pop",
"time": "2230-0145",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Wala Wala",
"artiste": "53A",
"genre": "Pop Rock",
"time": "1900",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Wala Wala",
"artiste": "The Common People",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/8/2011",
"day": "Friday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Acid Bar",
"artiste": "Faisal",
"genre": "Acoustic",
"time": "1900-2100",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Acid Bar",
"artiste": "Kulture",
"genre": "Acoustic",
"time": "2130-0015",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Acid Bar",
"artiste": "Sugarlove",
"genre": "Acoustic",
"time": "0030-0215",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Blujaz Cafe",
"artiste": "Ayaschool",
"genre": "Jazz",
"time": "2130",
"price": "$$ *Free entry",
"description": "Ayaschool visits Blu Jaz Cafe on Saturdays where Aya Sekine brings friends like DJ KoFlow, Alemay Fernandez, Angelita Li, Fendi, Budi to the mic. And by her second set, she brings down the house with her incredible improvisation and energy.",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Brix",
"artiste": "Shades",
"genre": "R&B; Soul; Calypso",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "China One",
"artiste": "Tabula (Full Band) and DJ Tovan",
"genre": "",
"time": "2100",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Crazy Elephant",
"artiste": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Esplanade Concert Hall",
"artiste": "Colours of the Wind东西双笛韵",
"genre": "Classical; Chinese",
"time": "1930",
"price": "$25*, $35**, $55, $75, $95 Concessions: Limited concessions for students, NSF & senior citizens: $14* / $19**",
"description": "A dialogue between recorder and dizi 西洋竖笛和中国竹笛的对话 Co-produced by Esplanade – Theatres on the Bay and Singapore Chinese Orchestra. 由新加坡华乐团呈献，与滨海艺术中心联合制作",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Highlander",
"artiste": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Hood",
"artiste": "Pennylane Band",
"genre": "",
"time": "",
"price": "Free (excl F&B)",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Quarubar",
"artiste": "Alemay & Shawn Letts",
"genre": "Jazz; Latin; Tango",
"time": "",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Timbre Arts House",
"artiste": "Iris Feat. Liza",
"genre": "Rock",
"time": "2130-1245",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Timbre Old School",
"artiste": "Sofia & Fatt",
"genre": "Rock",
"time": "2115-1230",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Timbre Substation",
"artiste": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Wala Wala",
"artiste": "The Unexpected",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "Free (excl F&B)",
"description": "none",
},
{
"date": "7/9/2011",
"day": "Saturday",
"place_name": "Yello Jello Retrobar",
"artiste": "",
"genre": "",
"time": "",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Acid Bar",
"artiste": "Sugarlove",
"genre": "Acoustic",
"time": "2100-0030",
"price": "$$$ + $20 cover",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Crazy Elephant",
"artiste": "Jam Session",
"genre": "Blues",
"time": "2200",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Esplanade Concert Hall",
"artiste": "Sparks Goes POP! Sparks流行风!",
"genre": "Classical; Chinese",
"time": "1500",
"price": "Free",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Esplanade Recital Studio",
"artiste": "The Tryst",
"genre": "",
"time": "1930",
"price": "$24Concessions: for students, NSF and senior citizens: $16",
"description": "Intimate encounters with four late 20th century composers at the disco, in a garden and on the road, all after violin and piano have taken a Scottish love poem and weaved their own tender embraces around it. Dutch composer Louis Andriessen says of his modern take on the dance hall, \"Nothing goes smoothly any more\", while, in characteristically mystic and misty vein, Japan's greatest 20th century composer declares \"I would like to achieve a sound as intense as silence\". For his part, John Adams describes his 1995 piece for violin and piano as beginning with \"a relaxed drive down a not unfamiliar road\" and ending with \"a giddy, bouncy ride for four wheel drives only\". It all sounds pretty frenetic but, again to quote Adams, \"Relax, and let us do the driving!\"",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Hood",
"artiste": "Victor Tang",
"genre": "",
"time": "",
"price": "$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "The Pump Room",
"artiste": "Jive Talkin'",
"genre": "Pop, Rock, Jazz",
"time": "2245",
"price": "$$$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Timbre Substation",
"artiste": "Timbre Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Wala Wala",
"artiste": "Jack & Rai",
"genre": "Pop Rock",
"time": "Prime Time",
"price": "$$ *Free entry",
"description": "none",
},
{
"date": "7/10/2011",
"day": "Sunday",
"place_name": "Yello Jello Retrobar",
"artiste": "John Molina & Krueger",
"genre": "Rock",
"time": "2200",
"price": "$$ *Free entry",
"description": "none",
},
]
