events = [
{
"date": "17 Oct 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "classic; jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "17 Oct 11",
"place": "Beer Market",
"name": "Phoebee and Dayvid",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "17 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "17 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "17 Oct 11",
"place": "Timbre Arts House",
"name": "Surath & Rene",
"genre": "Pop Rock",
"time": "2030-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "17 Oct 11",
"place": "Timbre Old School",
"name": "Pam & Chris",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "17 Oct 11",
"place": "Timbre Substation",
"name": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "18 Oct 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "18 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "18 Oct 11",
"place": "Esplanade Theatre",
"name": "Rays of Hope- NCCS Charity Concert",
"genre": "Pop",
"time": "2000",
"price": "$38-208",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=hope1011",
},
{
"date": "18 Oct 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "18 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "18 Oct 11",
"place": "Tab Singapore",
"name": "Mel & Khim",
"genre": "Pop",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/mel-khim/",
},
{
"date": "18 Oct 11",
"place": "The Pigeonhole",
"name": "Bushwalla",
"genre": "Pop Rock",
"time": "2000",
"price": "Free",
"website": "http://www.thepigeonhole.com.sg/",
},
{
"date": "18 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "18 Oct 11",
"place": "Timbre Arts House",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "18 Oct 11",
"place": "Timbre Old School",
"name": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "18 Oct 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "18 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "19 Oct 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "19 Oct 11",
"place": "Broun",
"name": "Polkadot & Moonbeam",
"genre": "Jazz; Contemporary",
"time": "1930-2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
},
{
"date": "19 Oct 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "19 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "19 Oct 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "19 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "19 Oct 11",
"place": "Paulaner Brauhaus",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "1900-2100",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "19 Oct 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/the-next-movement/",
},
{
"date": "19 Oct 11",
"place": "Tab Singapore",
"name": "Bevlyn ft Kevin Matthews",
"genre": "Indie; Jazz",
"time": "2030",
"price": "$25",
"website": "http://www.tab.com.sg/2011/01/bevlyn-khoo/",
},
{
"date": "19 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "19 Oct 11",
"place": "Timbre Arts House",
"name": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "19 Oct 11",
"place": "Timbre Old School",
"name": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "19 Oct 11",
"place": "Timbre Substation",
"name": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "19 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "20 Oct 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "20 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "20 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "20 Oct 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "20 Oct 11",
"place": "Hard Rock Café",
"name": "Michaela Therese, Rebecca Burch, Cove Red, Shigga Shay",
"genre": "Pop",
"time": "",
"price": "Free",
"website": "http://www.timeoutsingapore.com/music/feature/alive-and-kicking-oct-2011",
},
{
"date": "20 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "20 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "20 Oct 11",
"place": "Timbre Arts House",
"name": "The Common People",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "20 Oct 11",
"place": "Timbre Old School",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "20 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "Pleasantry",
"genre": "Rock",
"time": "2030-2130",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "20 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "Cheating Sons",
"genre": "Indie; Folk",
"time": "2230-2330",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "20 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "Goodfellas",
"genre": "Rock",
"time": "2200-2300",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "20 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "Goodfellas",
"genre": "Rock",
"time": "2330-0030",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "20 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "21 Oct 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "21 Oct 11",
"place": "Broun",
"name": "Offside",
"genre": "Top 40's",
"time": "1930-2015",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
},
{
"date": "21 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "21 Oct 11",
"place": "Esplanade Concert Hall",
"name": "Mahler's Seventh (Singapore Symphonic Orchestra)",
"genre": "Classical",
"time": "1930",
"price": "$15-$72",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=essoe211011",
},
{
"date": "21 Oct 11",
"place": "Esplanade Outdoor Theatre",
"name": "Fusion Smusion",
"genre": "Fusion; Smooth Jazz",
"time": "Various",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/otw_fusion_smusion/index.jsp",
},
{
"date": "21 Oct 11",
"place": "Esplanade Theatre",
"name": "Dhoom Machale, Pritam ft. Mohit Chauhan",
"genre": "Indian",
"time": "2000",
"price": "$45-225",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=pritam1011",
},
{
"date": "21 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "21 Oct 11",
"place": "Grand Theater, Marina Bay Sands",
"name": "Yanni in Concert",
"genre": "New Age",
"time": "1930",
"price": "$128-288",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=yanni1011",
},
{
"date": "21 Oct 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "21 Oct 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "21 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "21 Oct 11",
"place": "Paulaner Brauhaus",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "1900-2100",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "21 Oct 11",
"place": "Tab Singapore",
"name": "Mel & Khim",
"genre": "Pop",
"time": "1930",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/mel-khim/",
},
{
"date": "21 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "21 Oct 11",
"place": "Timbre Arts House",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "21 Oct 11",
"place": "Timbre Old School",
"name": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "The Marilyns",
"genre": "Pop Rock",
"time": "2100-2200",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "New Jersey (Bon Jovi Tribute Band)",
"genre": "Rock",
"time": "2315-0000",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "New Jersey (Bon Jovi Tribute Band)",
"genre": "Rock",
"time": "0030-0115 (early 22nd morn)",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "53A",
"genre": "Pop Rock",
"time": "2230-2315",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "53A",
"genre": "Pop Rock",
"time": "2345-0030",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "53A",
"genre": "Pop Rock",
"time": "0100-0145 (early 22nd morn)",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "21 Oct 11",
"place": "Wala Wala Café Bar",
"name": "The Common People",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "21 Oct 11",
"place": "Siloso Beach",
"name": "Fuze Collective & M.I.G",
"genre": "Jazz; Funk",
"time": "2000",
"price": "Free",
"website": "http://www.sentosa.com.sg/en/whats-on/events/current-events/#item3257/",
},
{
"date": "22 Oct 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2230",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "22 Oct 11",
"place": "Broun",
"name": "Cows on a boat",
"genre": "Pop; Jazz",
"time": "1930-2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
},
{
"date": "22 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "22 Oct 11",
"place": "Esplanade Outdoor Theatre",
"name": "Fusion Smusion",
"genre": "Fusion; Smooth Jazz",
"time": "Various",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/otw_fusion_smusion/index.jsp",
},
{
"date": "22 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "22 Oct 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "22 Oct 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "22 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "22 Oct 11",
"place": "Hood Bar & Café",
"name": "Manhand (Malayisa HipHop band)",
"genre": "Hip Hop",
"time": "",
"price": "Free + F&B Charges",
"website": "http://www.hoodbarandcafe.com/",
},
{
"date": "22 Oct 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/the-next-movement/",
},
{
"date": "22 Oct 11",
"place": "The Pigeonhole",
"name": "Nicholas Chim ft. Monster Cat (Opening)",
"genre": "Indie; Folk",
"time": "2100",
"price": "$15",
"website": "http://www.facebook.com/the.pigeonhole/posts/171949642886590",
},
{
"date": "22 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "22 Oct 11",
"place": "Timbre Arts House",
"name": "The Common People",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "22 Oct 11",
"place": "Timbre Old School",
"name": "Sofia & Fatt",
"genre": "Pop Rock",
"time": "2115-1230",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "22 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "New Jersey (Bon Jovi Tribute Band)",
"genre": "Rock",
"time": "2200-2315",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "22 Oct 11",
"place": "Timbre Substation (Roktober stage)",
"name": "New Jersey (Bon Jovi Tribute Band)",
"genre": "Rock",
"time": "0000-0115 (early 23 morn)",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "22 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "2300-2400",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "22 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "0100-0200 (early 23 morn)",
"price": "Free + F&B Charges",
"website": "http://i54.tinypic.com/vykrcx.jpg",
},
{
"date": "22 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "23 Oct 11",
"place": "Crazy Elephant",
"name": "Jam Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "23 Oct 11",
"place": "Esplanade Outdoor Theatre",
"name": "Fusion Smusion",
"genre": "Fusion; Smooth Jazz",
"time": "Various",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/otw_fusion_smusion/index.jsp",
},
{
"date": "23 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "23 Oct 11",
"place": "Timbre Substation (Substation stage)",
"name": "Blues Jam",
"genre": "Blues",
"time": "1930-2400",
"price": "Free + F&B Charges / Optional paid Buffet",
"website": "http://www.sistic.com.sg/portal/dt?retry=1&dt.provider=PortletWindowProcessChannel&dt.action=process&dt.window.portletAction=RENDER&dt.containerName=JSPTabContainer/sEventsCalendar&contentCode=bbq1011&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.windowProvider.currentChannelMode=VIEW&dt.isPortletRequest=true",
},
{
"date": "23 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Jack & Rai",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "24 Oct 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "classic; jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "24 Oct 11",
"place": "Beer Market",
"name": "Phoebee and Dayvid",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "24 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "24 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "24 Oct 11",
"place": "Timbre Arts House",
"name": "Surath & Rene",
"genre": "Pop Rock",
"time": "2030-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "24 Oct 11",
"place": "Timbre Old School",
"name": "Pam & Chris",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "24 Oct 11",
"place": "Timbre Substation",
"name": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "25 Oct 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "25 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "25 Oct 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "25 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "25 Oct 11",
"place": "Tab Singapore",
"name": "Mel & Khim",
"genre": "Pop",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/mel-khim/",
},
{
"date": "25 Oct 11",
"place": "The Pigeonhole",
"name": "Open Mic (Open)",
"genre": "-",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/the.pigeonhole",
},
{
"date": "25 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "25 Oct 11",
"place": "Timbre Arts House",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "25 Oct 11",
"place": "Timbre Old School",
"name": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "25 Oct 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "25 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "26 Oct 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "26 Oct 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "26 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "26 Oct 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "26 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "26 Oct 11",
"place": "Paulaner Brauhaus",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "1900-2100",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "26 Oct 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/the-next-movement/",
},
{
"date": "26 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "26 Oct 11",
"place": "Timbre Arts House",
"name": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Oct 11",
"place": "Timbre Old School",
"name": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Oct 11",
"place": "Timbre Substation",
"name": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "26 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "27 Oct 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "27 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "27 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "27 Oct 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "27 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "27 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "27 Oct 11",
"place": "Timbre Arts House",
"name": "The Common People",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Oct 11",
"place": "Timbre Old School",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Oct 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "27 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "28 Oct 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "28 Oct 11",
"place": "Broun",
"name": "Cove Red",
"genre": "Singer Songwriter",
"time": "1930-2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
},
{
"date": "28 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "28 Oct 11",
"place": "Esplanade Recital Studio",
"name": "Randolf Arriola",
"genre": "Vitruoso",
"time": "2130",
"price": "$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=randolf1011",
},
{
"date": "28 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "28 Oct 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "28 Oct 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "28 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "28 Oct 11",
"place": "Paulaner Brauhaus",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "1900-2100",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "28 Oct 11",
"place": "Tab Singapore",
"name": "Mel & Khim",
"genre": "Pop",
"time": "1930",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/mel-khim/",
},
{
"date": "28 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "28 Oct 11",
"place": "Timbre Arts House",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Oct 11",
"place": "Timbre Old School",
"name": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Oct 11",
"place": "Timbre Substation",
"name": "53A",
"genre": "Pop",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "28 Oct 11",
"place": "Wala Wala Café Bar",
"name": "The Common People",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "28 Oct 11",
"place": "Siloso Beach",
"name": "Ireson Band & Anne Weerapass",
"genre": "Jazz; Latin",
"time": "2000",
"price": "Free",
"website": "http://www.sentosa.com.sg/en/whats-on/events/current-events/#item3257/",
},
{
"date": "29 Oct 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2230",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "29 Oct 11",
"place": "Broun",
"name": "Michelle Maxine",
"genre": "Pop",
"time": "1930-2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
},
{
"date": "29 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "29 Oct 11",
"place": "Fort Canning Park",
"name": "Wildfire Festival: Mutaytor, Wicked Aura, Sixx etc.",
"genre": "Various",
"time": "1700",
"price": "$55-$65",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=fire1011",
},
{
"date": "29 Oct 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "29 Oct 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "29 Oct 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "29 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "29 Oct 11",
"place": "Hood Bar & Café",
"name": "Opposition Party",
"genre": "",
"time": "",
"price": "Free + F&B Charges",
"website": "http://www.hoodbarandcafe.com/",
},
{
"date": "29 Oct 11",
"place": "Singapore Indoor Stadium",
"name": "Faye Wong 2011 Concert Tour",
"genre": "Chinese; Pop",
"time": "2000",
"price": "$120-480",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=faye1011",
},
{
"date": "29 Oct 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.tab.com.sg/2011/01/the-next-movement/",
},
{
"date": "29 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "29 Oct 11",
"place": "Timbre Arts House",
"name": "The Common People",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Oct 11",
"place": "Timbre Old School",
"name": "Sofia & Fatt",
"genre": "Pop Rock",
"time": "2115-1230",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Oct 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "29 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "30 Oct 11",
"place": "Crazy Elephant",
"name": "Jam Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "30 Oct 11",
"place": "The Pump Room @ Clarke Quay",
"name": "Jive Talkin'",
"genre": "Pop; Rock; Jazz",
"time": "2245",
"price": "Free + F&B Charges",
"website": "http://www.pumproomasia.com/home.html",
},
{
"date": "30 Oct 11",
"place": "Timbre Substation",
"name": "Timbre Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
},
{
"date": "30 Oct 11",
"place": "Wala Wala Café Bar",
"name": "Jack & Rai",
"genre": "Pop Rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "31 Oct 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Cassic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "31 Oct 11",
"place": "Beer Market",
"name": "Phoebee and Dayvid",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "31 Oct 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "31 Oct 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "1 Nov 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "1 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "1 Nov 11",
"place": "Esplanade Concert Hall",
"name": "Mozart Madness",
"genre": "Classical",
"time": "1930",
"price": "$28-$68",
"website": "http://www.esplanade.com/whats_on/programme_info/mozart_madness/index.jsp",
},
{
"date": "1 Nov 11",
"place": "Fort Canning Park",
"name": "Whitesnake- Forevermore Tour",
"genre": "Rock",
"time": "2000",
"price": "$110-$140",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=snake1111",
},
{
"date": "1 Nov 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "1 Nov 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "2 Nov 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "2 Nov 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "2 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "2 Nov 11",
"place": "Esplanade Theatre",
"name": "k.d. lang & the Siss Boom Bang",
"genre": "Pop",
"time": "2000",
"price": "$40-$120",
"website": "http://www.esplanade.com/whats_on/programme_info/kd_lang_and_the_siss_boom_band/index.jsp",
},
{
"date": "2 Nov 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "2 Nov 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "3 Nov 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "3 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "3 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "3 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "3 Nov 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "4 Nov 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "4 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "4 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "4 Nov 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "4 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "4 Nov 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "5 Nov 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2230",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "5 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "5 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "5 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "5 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "5 Nov 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
},
{
"date": "5 Nov 11",
"place": "The Pigeonhole",
"name": "Deserters (MY) & Bottlesmokers (ID)",
"genre": "Indie; Electro",
"time": "2000",
"price": "$10",
"website": "http://www.thepigeonhole.com.sg/",
},
{
"date": "6 Nov 11",
"place": "Crazy Elephant",
"name": "Jam Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "7 Nov 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Cassic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "7 Nov 11",
"place": "Beer Market",
"name": "Phoebee and Dayvid",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "7 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "8 Nov 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "8 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "8 Nov 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "9 Nov 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "9 Nov 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "9 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "9 Nov 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "10 Nov 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "10 Nov 11",
"place": "Blujaz Café",
"name": "Chok Kerong: \"Good Company\" CD release",
"genre": "Jazz",
"time": "2030-2330",
"price": "$15",
"website": "www.kerongchok.com",
},
{
"date": "10 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "10 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "10 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "11 Nov 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "11 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "11 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "11 Nov 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "11 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "12 Nov 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2230",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
},
{
"date": "12 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "12 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "12 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "12 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "13 Nov 11",
"place": "Crazy Elephant",
"name": "Jam Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "14 Nov 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Cassic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "14 Nov 11",
"place": "Crazy Elephant",
"name": "Crazy Elephant Band",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/",
},
{
"date": "15 Nov 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "16 Nov 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "16 Nov 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "17 Nov 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "17 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "17 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "18 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "18 Nov 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "18 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "19 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "19 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "19 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "21 Nov 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Cassic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "22 Nov 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "23 Nov 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "23 Nov 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "24 Nov 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
{
"date": "24 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "24 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "25 Nov 11",
"place": "Esplanade Recital Studio",
"name": "Syndicate Sessions: Octover, Kiat & Max Lane, KoFlow & Aya Sekine",
"genre": "Electro; Jazz",
"time": "2130-2300",
"price": "$25",
"website": "http://syndicate.sg/2011/10/esplanade-syndicate-sessions-2011/",
},
{
"date": "25 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "25 Nov 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "25 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "26 Nov 11",
"place": "Fullerton Bay hotel",
"name": "Claressa Monteiro",
"genre": "Jazz",
"time": "1930-2215",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/TheFullertonBayHotel",
},
{
"date": "26 Nov 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrock.com",
},
{
"date": "26 Nov 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
},
{
"date": "28 Nov 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Cassic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
},
{
"date": "30 Nov 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
},
]
