events = [
{
"date": "20 Dec 11",
"place": "Acidbar",
"name": "Joshua Alexis",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Acidbar",
"name": "Kulture",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglican High School Choir",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglican_high_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglican High School Choir",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglican_high_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Esplanade Recital Studio",
"name": "The Ancient Voice",
"genre": "Mandarin; Classical;",
"time": "1930",
"price": "$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=tav1211",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Hard Rock Café",
"name": "Unified",
"genre": "Top 40's; Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/hardrockcafesingapore?sk=info",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Pop; Rock; Top 40's",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Hood Bar & Café",
"name": "S'pore Char Siew Baos",
"genre": "Jazz; Pop; Chinese; Hokkien",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Quarubar",
"name": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Tab Singapore",
"name": "Kyle Patrick (of the Click Five) (USA)",
"genre": "Pop; Acoustic",
"time": "1900",
"price": "$45/$65",
"website": "http://www.tab.com.sg/2011/01/kyle-patrick/",
"non_regular": "y",
"special": "y",
"blurp": "Sing along to classic Christmas songs, your favourite Click Five songs and an exclusive preview of Kyle Patrick's upcoming solo album!",
},
{
"date": "20 Dec 11",
"place": "Timbre Arts House",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Timbre Old School",
"name": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Acidbar",
"name": "Jamiel",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Acidbar",
"name": "Pam & Fatt",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "1930",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Broun",
"name": "Polkadot and Moonbeam",
"genre": "Jazz; Contemporary",
"time": "1930 - 2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0048",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Esplanade Concourse",
"name": "St Anthony's Canossian Secondary School Choir",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_st_anthonys_canossian_secondary_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Esplanade Concourse",
"name": "St Anthony's Canossian Secondary School Choir",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_st_anthonys_canossian_secondary_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Hard Rock Café",
"name": "Six In The City ft. Tabula",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/hardrockcafesingapore?sk=info",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Pop; Rock; Top 40's",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Hood Bar & Café",
"name": "Ling Kai and Susanna",
"genre": "Acoustic",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Octapas (Spanish Tapas Bar)",
"name": "In Control",
"genre": "Pop; Rock; Top 40's",
"time": "2130-2430",
"price": "Free + F&B Charges",
"website": "http://www.octapasasia.com/contact_us.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Quarubar",
"name": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2030",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "The Pigeonhole",
"name": "Cheating Sons",
"genre": "Blues; Rock & Roll",
"time": "2030-2230",
"price": "Free",
"website": "http://www.facebook.com/event.php?eid=270414166328112",
"non_regular": "y",
"special": "y",
"blurp": "The Sons are 5 local musicians rooted by the blues and rock’n’roll. Watch them perform their debut album Masters, Wives, Daughter live!",
},
{
"date": "21 Dec 11",
"place": "Timbre Arts House",
"name": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Timbre Old School",
"name": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Timbre Substation",
"name": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Acidbar",
"name": "Nelson",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Acidbar",
"name": "Tuna Pop",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Barossa Bar Holland Village",
"name": "Tigerlilies",
"genre": "Pop; Rock; Top 40's",
"time": "2030 - 0030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/pages/Barossa-Bar-Holland-Village/138903096204244?sk=wall",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Black Box @ Goodman Arts Centre",
"name": "Inch Chua & The Metric System @ xxiii",
"genre": "Acoustic",
"time": "2000 - 2200",
"price": "$18",
"website": "http://www.facebook.com/events/203390653069999/",
"non_regular": "y",
"special": "y",
"blurp": "Inch Chua is back, together with The Metric System, they bring you crowd pleasers and festive cheer!",
},
{
"date": "22 Dec 11",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglo-Chinese Junior College Choir",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglo-chinese_junior_college_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglo-Chinese Junior College Choir",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglo-chinese_junior_college_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Acoustic Set",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/hardrockcafesingapore?sk=info",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Highlander",
"name": "Dejavu",
"genre": "Pop; Rock; Top 40's",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.highlanderasia.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Hood Bar & Café",
"name": "Howie and Nelson",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Octapas (Spanish Tapas Bar)",
"name": "In Control",
"genre": "Pop; Rock; Top 40's",
"time": "2130-2430",
"price": "Free + F&B Charges",
"website": "http://www.octapasasia.com/contact_us.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Quarubar",
"name": "Wayne Sandz & Wayne Gideon",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Tab Singapore",
"name": "Shili & Adi",
"genre": "Pop Rock",
"time": "2032-2330",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Timbre Arts House",
"name": "Today's Special",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Timbre Old School",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Acidbar",
"name": "Matt",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Acidbar",
"name": "Sofia & Fatt",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Barossa Bar Holland Village",
"name": "Pennylane Band",
"genre": "Pop; Rock; Top 40's",
"time": "2130 - 0100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/pages/Barossa-Bar-Holland-Village/138903096204244?sk=wall",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Esplanade Concourse",
"name": "River Valley Chamber Singers",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_river_valley_chamber_singers/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Esplanade Concourse",
"name": "River Valley Chamber Singers",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_river_valley_chamber_singers/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Hard Rock Café",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/hardrockcafesingapore?sk=info",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Hard Rock Café Sentosa",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Home Club",
"name": "Home Club Presents Beat!'s 5.6th Birthday",
"genre": "Indie Rock",
"time": "2000",
"price": "$15 + 1 Drink",
"website": "http://www.facebook.com/events/265097546877081/",
"non_regular": "y",
"special": "y",
"blurp": "Home Club presents BEAT!'s birthday with cool local indie bands celebrating 5.6 years of indie goodness!",
},
{
"date": "23 Dec 11",
"place": "Hood Bar & Café",
"name": "Timmy! Band",
"genre": "Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Octapas (Spanish Tapas Bar)",
"name": "In Control",
"genre": "Pop; Rock; Top 40's",
"time": "2130-0145",
"price": "Free + F&B Charges",
"website": "http://www.octapasasia.com/contact_us.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Prince of Wales",
"name": "The Disclaimers",
"genre": "Rock",
"time": "2130 - 0100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/events/243666812370390/",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Quarubar",
"name": "Michaela Therese & Joe Jayaveeran",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Tab Singapore",
"name": "Mel & Rox",
"genre": "Pop; Classic; R&B",
"time": "1930",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Timbre Arts House",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Timbre Old School",
"name": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Timbre Substation",
"name": "53A",
"genre": "Pop",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Wala Wala Café Bar",
"name": "The Common People",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Dec 11",
"place": "Zouk",
"name": "ONE LOVE, ONE DANCE, ONE CHRISTMAS with Heidi (CAN) & Magda (GER)",
"genre": "Electronica; House; Techno; Disco",
"time": "2200",
"price": "$25/$32 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3627",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "0045 - 0215 (early 12th morning)",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Acidbar",
"name": "Faisal",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Acidbar",
"name": "Kulture",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "0045 - 0215 (early 13th morning)",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglican High School Choir",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglican_high_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Esplanade Concourse",
"name": "Anglican High School Choir",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_anglican_high_school_choir/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Hard Rock Café",
"name": "Enigma",
"genre": "Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/hardrockcafesingapore?sk=info",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Hard Rock Café Sentosa",
"name": "Energy",
"genre": "Rock",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.hardrockhotelsingapore.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Hood Bar & Café",
"name": "Pennylane Band",
"genre": "Rock & Roll",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Octapas (Spanish Tapas Bar)",
"name": "In Control",
"genre": "Pop; Rock; Top 40's",
"time": "2130-0145",
"price": "Free + F&B Charges",
"website": "http://www.octapasasia.com/contact_us.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Quarubar",
"name": "Alemay Fernandez & Shawn Letts",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Timbre Arts House",
"name": "Today's Special",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Timbre Old School",
"name": "Sofia, Surath & Luthfi",
"genre": "Pop Rock",
"time": "2115-1230",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Dec 11",
"place": "Zouk",
"name": "ONE LOVE, ONE DANCE, ONE CHRISTMAS with Ferry Corsten",
"genre": "Trance; Progressive",
"time": "2200",
"price": "$40 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3628",
"non_regular": "y",
"special": "y",
"blurp": "Let award-winning Ferry Corsten, a superstar trance and progressive DJ captivate your imagination this Christmas!",
},
{
"date": "25 Dec 11",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "1900 - 0015",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Esplanade Concourse",
"name": "The Vocal Consort",
"genre": "Choral",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_the_vocal_consort/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Esplanade Concourse",
"name": "The Vocal Consort",
"genre": "Choral",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_the_vocal_consort/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Esplanade Concourse",
"name": "The Vocal Consort",
"genre": "Choral",
"time": "2115",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_the_vocal_consort/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Hood Bar & Café",
"name": "Victor Tang",
"genre": "Alternative Rock",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/photo.php?fbid=267213796653836&set=a.117409888300895.6344.115969195111631&type=1&theater",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Timbre Substation",
"name": "Timbre Music Academy All Stars",
"genre": "Pop",
"time": "2145-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Velvet Underground",
"name": "Dimitri From Paris (FRA)",
"genre": "House; Disco",
"time": "2200",
"price": "$28/$35 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3630",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Jack & Rai",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Dec 11",
"place": "Zouk",
"name": "Dubfire (USA)",
"genre": "House; Techno; Electronica",
"time": "2200",
"price": "$28/$35 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3629",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Acidbar",
"name": "Nelson",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Acidbar",
"name": "Tuna Pop",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Balaclava",
"name": "Wendy & David",
"genre": "Classic; Jazz",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Beer Market",
"name": "Phoebee and Dayvid",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Esplanade Concourse",
"name": "A Flutely Affair with Jin How",
"genre": "Pop; Classical",
"time": "1815",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_a_flutey_affair_with_jin_how/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Esplanade Concourse",
"name": "A Flutely Affair with Jin How",
"genre": "Pop; Classical",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_a_flutey_affair_with_jin_how/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Esplanade Concourse",
"name": "A Flutely Affair with Jin How",
"genre": "Pop; Classical",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_a_flutey_affair_with_jin_how/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Hood Bar & Café",
"name": "Wanyue",
"genre": "English; Mandarin; Pop",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Quarubar",
"name": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Timbre Arts House",
"name": "Surath & Rene",
"genre": "Pop Rock",
"time": "2030-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Timbre Old School",
"name": "Pam & Chris",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Dec 11",
"place": "Timbre Substation",
"name": "Michaela Therese",
"genre": "Jazz",
"time": "2215-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Acidbar",
"name": "Joshua Alexis",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Acidbar",
"name": "Kulture",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Beer Market",
"name": "Howie, Nelson and Jez",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Esplanade Concourse",
"name": "TiGaia",
"genre": "Various",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_tigaia/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Esplanade Concourse",
"name": "TiGaia",
"genre": "Various",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_tigaia/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Hood Bar & Café",
"name": "S'pore Char Siew Baos",
"genre": "Jazz; Pop; Chinese; Hokkien",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Quarubar",
"name": "Dawn Ho & Munir Alsagoff",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Tab Singapore",
"name": "Mel & Rox",
"genre": "Pop; Classic; R&B",
"time": "2030",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Timbre Arts House",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Timbre Old School",
"name": "Fatt, Shili & Adi",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Tabula",
"genre": "Top 40's; Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Acidbar",
"name": "Jamiel",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Acidbar",
"name": "Pam & Fatt",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "1930",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Broun",
"name": "Polkadot and Moonbeam",
"genre": "Jazz; Contemporary",
"time": "1930 - 2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "CM-PB",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2130-0049",
"price": "Free + F&B Charges",
"website": "http://www.screamquiet.com/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Esplanade Concourse",
"name": "Loke Hoe Kit",
"genre": "Various; Classical",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_loke_hoe_kit/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Esplanade Concourse",
"name": "Loke Hoe Kit",
"genre": "Various; Classical",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_loke_hoe_kit/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Hood Bar & Café",
"name": "Ling Kai and Susanna",
"genre": "Acoustic",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Quarubar",
"name": "Lily Nuris & Wayne Sandz",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Tab Singapore",
"name": "The Next Movement",
"genre": "Pop; Soul; R&B",
"time": "2030",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Timbre Arts House",
"name": "Enigma",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Timbre Old School",
"name": "Luthfi & Simon",
"genre": "Pop Rock",
"time": "1945-2300",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Timbre Substation",
"name": "Raw Earth",
"genre": "Rock",
"time": "2115-0030",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Timmy ft. Ngak",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Acidbar",
"name": "Nelson",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Acidbar",
"name": "Tuna Pop",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Barossa Bar Holland Village",
"name": "Tigerlilies",
"genre": "Pop; Rock; Top 40's",
"time": "2030 - 0030",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/pages/Barossa-Bar-Holland-Village/138903096204244?sk=wall",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Beer Market",
"name": "Zsa + Claire",
"genre": "Pop; Folk",
"time": "2030",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Broun",
"name": "Dawn Loy",
"genre": "Acoustic; Pop",
"time": "1930 - 2130",
"price": "Free + F&B Charges",
"website": "http://broun.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Esplanade Concourse",
"name": "ExtraOrdinary Horizons",
"genre": "Percussion",
"time": "1915",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_extraordinary_horizons/index.jsp#tabs",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Esplanade Concourse",
"name": "ExtraOrdinary Horizons",
"genre": "Percussion",
"time": "2015",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/atc_extraordinary_horizons/index.jsp#tabs",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Hood Bar & Café",
"name": "Howie and Nelson",
"genre": "Acoustic",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Quarubar",
"name": "Wayne Sandz & Wayne Gideon",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Tab Singapore",
"name": "Shili & Adi",
"genre": "Pop Rock",
"time": "2033-2330",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Timbre Arts House",
"name": "Today's Special",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Timbre Old School",
"name": "53A",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2215-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Acidbar",
"name": "Matt",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Acidbar",
"name": "Sofia & Fatt",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Barossa Bar Holland Village",
"name": "Pennylane Band",
"genre": "Pop; Rock; Top 40's",
"time": "2130 - 0100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/pages/Barossa-Bar-Holland-Village/138903096204244?sk=wall",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Beer Market",
"name": "Jack & Rai",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Hood Bar & Café",
"name": "Timmy! Band",
"genre": "Rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Quarubar",
"name": "Michaela Therese & Joe Jayaveeran",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Tab Singapore",
"name": "Mel & Rox",
"genre": "Pop; Classic; R&B",
"time": "1930",
"price": "Free",
"website": "http://www.tab.com.sg/2011/11/dec-2011/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Timbre Arts House",
"name": "Goodfellas",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Timbre Old School",
"name": "Sugarlove",
"genre": "Pop Rock",
"time": "2015-2330",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Timbre Substation",
"name": "53A",
"genre": "Pop",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Wala Wala Café Bar",
"name": "The Common People",
"genre": "Pop rock",
"time": "-",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Dec 11",
"place": "Zouk",
"name": "Infected Mushroom LIVE! (ISR)",
"genre": "Psychedelic; Trance; Electronica",
"time": "2200",
"price": "$25/$32 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3631",
"non_regular": "y",
"special": "y",
"blurp": "Singapore is no stranger to Psy-trance duo Infected Mushroom! This time LIVE at Zouk, don't miss this opportunity to catch them in action!",
},
{
"date": "31 Dec 11",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "0045 - 0215 (early 12th morning)",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Acidbar",
"name": "Faisal",
"genre": "Acoustic",
"time": "1900 - 2100",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Beer Market",
"name": "Elusion ft. Melissa",
"genre": "Pop Rock; Top 40's",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Beer Market",
"name": "Happy Hour Band",
"genre": "Pop Rock; Top 40's",
"time": "2000",
"price": "Free + F&B Charges",
"website": "http://www.beermarket.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Hood Bar & Café",
"name": "Ugly In The Morning",
"genre": "Funk; Blues; Rock",
"time": "2030 - 2130",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/ilovehood",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Quarubar",
"name": "Alemay Fernandez & Shawn Letts",
"genre": "Jazz; Latin; Tango",
"time": "2100",
"price": "Free + F&B Charges",
"website": "http://www.facebook.com/group.php?gid=46581108311",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Timbre Arts House",
"name": "Today's Special",
"genre": "Pop Rock",
"time": "2130-0045",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Timbre Old School",
"name": "Sofia, Surath & Luthfi",
"genre": "Pop Rock",
"time": "2115-1230",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Timbre Substation",
"name": "Goodfellas",
"genre": "Rock",
"time": "2230-0145",
"price": "Free + F&B Charges",
"website": "http://www.timbregroup.asia/timbresg/main.asp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Wala Wala Café Bar",
"name": "Shirlyn and the UnXpected",
"genre": "Pop rock",
"time": "2130",
"price": "Free + F&B Charges",
"website": "http://www.imaginings.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Dec 11",
"place": "Zouk",
"name": "Martin Solveig (FRA)",
"genre": "House; Electronica",
"time": "2200",
"price": "$40 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3632",
"non_regular": "y",
"special": "y",
"blurp": "From the guy who brought you the hit song \"Hello\", Martin Solveig is here to blow you away with french electro bangers on New Years' eve!",
},
{
"date": "1 Jan 12",
"place": "Acidbar",
"name": "Kulture",
"genre": "Acoustic",
"time": "2130 - 0045",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "1 Jan 12",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "0045 - 0215 (early 13th morning)",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "1 Jan 12",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "1 Jan 12",
"place": "Esplanade Theatre",
"name": "Keroncong Gala",
"genre": "Malay; Indonesian",
"time": "2000",
"price": "$28 - $88",
"website": "http://www.esplanade.com/whats_on/programme_info/kerongcong_gala/index.jsp",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "1 Jan 12",
"place": "Esplanade Theatre",
"name": "Pentas Esplanade's Keroncong Gala",
"genre": "",
"time": "2000",
"price": "$28/$48/$68/$88",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=keron0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "1 Jan 12",
"place": "Zouk",
"name": "Pete Tong (UK)",
"genre": "Electronica; House; Progressive",
"time": "2200",
"price": "$25/$32 + 2 Drinks",
"website": "http://www.zoukclub.com/#/events/detail/3633",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "2 Jan 12",
"place": "Acidbar",
"name": "Sugarlove",
"genre": "Acoustic",
"time": "1900 - 0015",
"price": "Free + F&B Charges",
"website": "http://www.peranakanplace.com/acidbar.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "2 Jan 12",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "2 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Coffee Morning & Afternoon Tea Best of the Rocking '60s",
"genre": "",
"time": "1030",
"price": "$12",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=coffee0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "2 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Coffee Morning & Afternoon Tea Best of the Rocking '60s",
"genre": "",
"time": "1500",
"price": "$12",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=coffee0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "3 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "4 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "5 Jan 12",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "Esplanade Concert Hall",
"name": "Mahler 5",
"genre": "",
"time": "1930",
"price": "$14/$16/$20/$22/$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=mahler0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Ivory Metal: An Evening of Piano & Gamelan Music",
"genre": "Classical",
"time": "2000",
"price": "$22/$30",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=ivory0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "SCO Concert Hall",
"name": "Rhapsodies of Spring 2012",
"genre": "",
"time": "2000",
"price": "$25/$35/$55/$75/$95",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=rhap0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "Singapore Indoor Stadium",
"name": "A-Mei Zhang Hui Mei AMeiZING World Tour 2012",
"genre": "Mandarin; Pop",
"time": "2000",
"price": "$98/$138/$168/$198/$228",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=amei0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Jan 12",
"place": "Zouk",
"name": "Aeroplane",
"genre": "Electronica",
"time": "2200",
"price": "TBA",
"website": "",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "7 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "7 Jan 12",
"place": "Esplanade Concert Hall",
"name": "SSO 33rd Anniversary Concert (SSO)",
"genre": "Classical",
"time": "1930",
"price": "$15/$22/$32/$42/$58/$72/$90",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=essoe070112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "7 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Ivory Metal: An Evening of Piano & Gamelan Music",
"genre": "Classical",
"time": "2000",
"price": "$22/$30",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=ivory0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "7 Jan 12",
"place": "SCO Concert Hall",
"name": "Rhapsodies of Spring 2013",
"genre": "",
"time": "2000",
"price": "$25/$35/$55/$75/$96",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=rhap0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "7 Jan 12",
"place": "Singapore Indoor Stadium",
"name": "A-Mei Zhang Hui Mei AMeiZING World Tour 2012",
"genre": "Mandarin; Pop",
"time": "2000",
"price": "$98/$138/$168/$198/$228",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=amei0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "8 Jan 12",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "9 Jan 12",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "9 Jan 12",
"place": "Fort Canning Park",
"name": "Scissor Sister Live in Singapore",
"genre": "Pop Rock; Glam Rock",
"time": "2000",
"price": "$88/$98/$110",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=scissor0112",
"non_regular": "y",
"special": "y",
"blurp": "This acclaimed New York disco pop group bring their infectious dance floor anthems to our island for the very first time!",
},
{
"date": "10 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "11 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "12 Jan 12",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "12 Jan 12",
"place": "Singapore Indoor Stadium",
"name": "Jam Hsiao World Tour 2012",
"genre": "Mandarin; Pop",
"time": "2000",
"price": "$88/$118/$138/$168",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=jam0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "13 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "13 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Late Nite @ Esplanade: Heritage",
"genre": "Experimental",
"time": "2130",
"price": "$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=heritage0112",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "13 Jan 12",
"place": "Zirca",
"name": "Skream & Benga",
"genre": "Dubstep; Electronica",
"time": "2200",
"price": "Before 11pm $20 - After 11pm $30/$32",
"website": "http://www.facebook.com/events/329497500413232/",
"non_regular": "y",
"special": "y",
"blurp": "Dubsteppers and UK Bass loyalists rejoice - the pioneers have arrived. SKREAM & BENGA are the duo who started it all and are undoubtedly the biggest names of the genre's global scene.",
},
{
"date": "14 Jan 12",
"place": "*SCAPE",
"name": "The People's Party",
"genre": "Indie",
"time": "1500 - 2200",
"price": "$108(One Day), $158/$178(Two Days)",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=pparty0112",
"non_regular": "y",
"special": "y",
"blurp": "Yet another indie festival to look forward to, with huge acts like Bombay Sapphire Club, The Naked and the Famous, Metronomy, etc!",
},
{
"date": "14 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "14 Jan 12",
"place": "Esplanade Concert Hall",
"name": "Harold In Italy (SSO)",
"genre": "Classical",
"time": "1930",
"price": "$15/$22/$32/$42/$58/$72/$90",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=essoe140112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "14 Jan 12",
"place": "Fort Canning Park",
"name": "Foster the People Live in Singapore",
"genre": "Indie Pop; Indie Rock",
"time": "2000",
"price": "$85/$95",
"website": "http://www.sistic.com.sg/portal/dt?retry=1&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&contentCode=foster0112&dt.isPortletRequest=true&dt.provider=PortletWindowProcessChannel&dt.containerName=JSPTabContainer/sEventsCalendar&dt.action=process&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER",
"non_regular": "y",
"special": "y",
"blurp": "Foster the People is no mystery to indie music lovers. Debuting their solid album \"Torches\", don't hesitate! Put on your pumped up kicks!",
},
{
"date": "14 Jan 12",
"place": "Zouk",
"name": "Yuksek",
"genre": "Electronica",
"time": "2200",
"price": "",
"website": "",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "15 Jan 12",
"place": "*SCAPE",
"name": "The People's Party",
"genre": "Indie",
"time": "1500 - 2200",
"price": "$108(One Day), $158/$178(Two Days)",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=pparty0112",
"non_regular": "y",
"special": "y",
"blurp": "Yet another indie festival to look forward to, with huge acts like Bombay Sapphire Club, The Naked and the Famous, Metronomy, etc!",
},
{
"date": "15 Jan 12",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "15 Jan 12",
"place": "Esplanade Concert Hall",
"name": "The Vocal Consort: 10th Aniversary Concert",
"genre": "",
"time": "1930",
"price": "$20/$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=consort0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "15 Jan 12",
"place": "Fort Canning Park",
"name": "Simple Plan",
"genre": "Punk Rock",
"time": "2000",
"price": "$99/$109/$121",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=simple0112",
"non_regular": "y",
"special": "y",
"blurp": "Familiar from our teenage years? Simple Plan continues to churn out highly infectious pop punk tunes that are featured on MTV charts.",
},
{
"date": "15 Jan 12",
"place": "MAX Pavilion @ Singapore Expo",
"name": "PLAY! With FTISLAND",
"genre": "Kpop",
"time": "1800",
"price": "$28/$108/$138/$168/$198",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=fti0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "15 Jan 12",
"place": "The Pigeonhole",
"name": "Lunarin",
"genre": "Alternative Rock",
"time": "2000",
"price": "Free",
"website": "http://www.thepigeonhole.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "16 Jan 12",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "17 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "18 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "18 Jan 12",
"place": "Esplanade Concert Hall",
"name": "GALA: Neema Jarvi & Vadim Repin (SSO)",
"genre": "",
"time": "1930",
"price": "$30/$42/$58/$78/$98/$128/$160",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=essoe180112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "18 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Suzanne Vega - LIVE!",
"genre": "Folk; Pop; Vocals",
"time": "1930",
"price": "$128/$148",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=vega0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "18 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Suzanne Vega",
"genre": "Folk; Acoustic",
"time": "1930 - 2130",
"price": "$128/$148",
"website": "http://www.facebook.com/events/216013905132598/",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "19 Jan 12",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "19 Jan 12",
"place": "Esplanade Concert Hall",
"name": "GALA: Neema Jarvi & Vadim Repin (SSO)",
"genre": "",
"time": "1930",
"price": "$30/$42/$58/$78/$98/$128/$160",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=essoe180112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "21 Jan 12",
"place": "Esplanade Concert Hall",
"name": "Klazz Brothers: Classic Meets Cuba",
"genre": "",
"time": "1930",
"price": "$35/$45/$55/$65/$85",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=klazz0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "22 Jan 12",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "23 Jan 12",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "24 Jan 12",
"place": "The Pigeonhole",
"name": "In Each Hand A Cutlass: Cinema of the Mind",
"genre": "Progressive Rock",
"time": "2000",
"price": "Free",
"website": "http://www.thepigeonhole.com.sg/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "25 Jan 12",
"place": "Home Club",
"name": "SBTRKT",
"genre": "Electronica",
"time": "2030",
"price": "$38/$45",
"website": "https://www.facebook.com/events/259304990796410/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "26 Jan 12",
"place": "Crazy Elephant",
"name": "Latitude One",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "27 Jan 12",
"place": "Esplanade Concert Hall",
"name": "Tan Dun Martial Arts Trilogy",
"genre": "Classical; Easten; Westen",
"time": "1930",
"price": "$38/$48/$68/$88/$108",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=tandun0112",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "28 Jan 12",
"place": "Crazy Elephant",
"name": "Blues Machine",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Jan 12",
"place": "Esplanade Concert Hall",
"name": "Tan Dun Martial Arts Trilogy",
"genre": "Classical; Easten; Westen",
"time": "1930",
"price": "$38/$48/$68/$88/$108",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=tandun0112",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "28 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Huayi - Chinese Festival of Arts 2012 Dreams by the Plum Blossoms",
"genre": "Mandarin; Classics",
"time": "1930",
"price": "$35",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=dreams0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Huayi - Chinese Festival of Arts 2012 Poetic Harmonies",
"genre": "Mandarin; Classics",
"time": "1500",
"price": "$35",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=poetic0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "28 Jan 12",
"place": "Singapore Indoor Stadium",
"name": "Search XPDC \"LIVE\" In Singapore",
"genre": "Rock",
"time": "2000",
"price": "$80/$100/$110/$130",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=xpdc0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Jan 12",
"place": "Crazy Elephant",
"name": "Jamming Session",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "29 Jan 12",
"place": "Esplanade Recital Studio",
"name": "Huayi - Chinese Festival of Arts 2012 In::music - Summer Lei + BIT Sound",
"genre": "Mandarin",
"time": "1930",
"price": "$25",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=summer0112",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "30 Jan 12",
"place": "Crazy Elephant",
"name": "Good Question",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "31 Jan 12",
"place": "Crazy Elephant",
"name": "Mean Jeanne",
"genre": "Blues",
"time": "2200",
"price": "Free + F&B Charges",
"website": "http://www.crazyelephant.com/index.html",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "4 Feb 12",
"place": "Esplanade Concert Hall",
"name": "Melodies of Classic Virtues: San Zi Jing and Di Zi Gui",
"genre": "Classical; Mandarin",
"time": "1930",
"price": "$38- $68",
"website": "http://www.esplanade.com/whats_on/programme_info/huayi12_melodies_of_classic_virtues/index.jsp",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "8 Feb 12",
"place": "Esplanade Recital Studio",
"name": "Paul Kelly",
"genre": "Rock; Acoustic; Folk",
"time": "2000 - 2130",
"price": "$68",
"website": "http://www.facebook.com/events/254948927890670/",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "8 Feb 12",
"place": "Fort Canning Park",
"name": "Kasabian",
"genre": "Indie Rock; Space Rock; Electronica",
"time": "2000",
"price": "$88",
"website": "http://www.live4music.com.sg/events/profile/518",
"non_regular": "y",
"special": "y",
"blurp": "This English alt-rock band needs no introduction. Their album topped #4 in the UK album charts, and hit singles in the UK Top 10 charts!",
},
{
"date": "9 Feb 12",
"place": "Fort Canning Park",
"name": "Opeth",
"genre": "Metal",
"time": "TBA",
"price": "TBA",
"website": "none",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "11 Feb 12",
"place": "The Pigeonhole",
"name": "Novak x Obedient Wives Club: A Family Affair",
"genre": "Indie",
"time": "2000 - 2200",
"price": "Free",
"website": "http://www.facebook.com/events/152286801540213/",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "12 Feb 12",
"place": "Esplanade Concert Hall",
"name": "Juzz Pop!",
"genre": "Pop",
"time": "1500",
"price": "Free",
"website": "http://www.esplanade.com/whats_on/programme_info/beau_sun_juzz_pop/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "12 Feb 12",
"place": "Fort Canning Park",
"name": "Laneway Festival Singapore 2012",
"genre": "Various",
"time": "-",
"price": "$135",
"website": "http://singapore.lanewayfestival.com.au/the-2012-singapore-st-jerome-s-laneway-festival-line-up/",
"non_regular": "y",
"special": "y",
"blurp": "The biggest indie festival yet! Featuring all the best indie bands in one place, it is the most insurgent and unique music event this year!",
},
{
"date": "14 Feb 12",
"place": "Esplanade Recital Studio",
"name": "Amor Peregrine",
"genre": "",
"time": "2130",
"price": "$25",
"website": "http://www.esplanade.com/whats_on/programme_info/amor_peregrine/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "18 Feb 12",
"place": "Singapore Indoor Stadium",
"name": "Super Show 4",
"genre": "Kpop",
"time": "1800",
"price": "TBA",
"website": "http://www.facebook.com/runningintothesun/posts/345088582184280",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "20 Feb 12",
"place": "Fort Canning Park",
"name": "Judas Priest ''The Epitaph Tour'' with Special Guest Lamb Of God",
"genre": "Metal",
"time": "1900",
"price": "$125 - $400",
"website": "http://www.sistic.com.sg/portal/dt?retry=1&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&contentCode=judas0212&dt.isPortletRequest=true&dt.provider=PortletWindowProcessChannel&dt.containerName=JSPTabContainer/sEventsCalendar&dt.action=process&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER",
"non_regular": "y",
"special": "y",
"blurp": "Need we say more? 2 of the biggest bands in the heavy metal scene coming together to bring you one rocking show, let the moshing begin!",
},
{
"date": "21 Feb 12",
"place": "Esplanade Concert Hall",
"name": "Dashboard Confessional (Solo Acoustic)",
"genre": "Rock; Acoustic",
"time": "2100 - 2230",
"price": "$48/$68/$88/$98",
"website": "http://www.facebook.com/events/252920364757410/",
"non_regular": "y",
"special": "y",
"blurp": "Dashboard Confessional returns to Singapore with a solo acoustic session, fans of D.C, grab your tickets before they are sold out!",
},
{
"date": "23 Feb 12",
"place": "Esplanade Concert Hall",
"name": "Rachael Yamagata",
"genre": "Pop; Indie; Blues",
"time": "2100 - 2230",
"price": "$48/$68/$88/$98",
"website": "http://www.facebook.com/events/216684661742979/",
"non_regular": "y",
"special": "y",
"blurp": "Singer-songwriter Rachael Yamagata returns to Singapore with a full length show,  be blown away by her amazing voice!",
},
{
"date": "24 Feb 12",
"place": "*SCAPE Lab",
"name": "A Skylit Drive & For This Cause",
"genre": "Hardcore",
"time": "1900 - 2200",
"price": "$40/$50",
"website": "https://www.facebook.com/events/242084682512506/",
"non_regular": "y",
"special": "y",
"blurp": "Hardcore band A Skylit Drive is set to rock Singapore's shores with their energy and melodies!",
},
{
"date": "25 Feb 12",
"place": "Singapore Indoor Stadium",
"name": "MAYDAY 2012 Nowhere World Tour Singapore",
"genre": "Mandarin; Pop",
"time": "2000",
"price": "$28/$108/$148/$188/$288",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=mayday0212",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "28 Feb 12",
"place": "Singapore Indoor Stadium",
"name": "a1, Blue and Jeff Timmons",
"genre": "Pop",
"time": "TBA",
"price": "TBA",
"website": "none",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "6 Mar 12",
"place": "Singapore Indoor Stadium",
"name": "ROXETTE Live in Singapore",
"genre": "Pop; Rock",
"time": "2000",
"price": "$98/$148/$188",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=roxette0312",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "7 Mar 12",
"place": "*SCAPE Lab",
"name": "Underoath",
"genre": "Hardcore",
"time": "1900 - 2100",
"price": "$50/$60",
"website": "http://www.facebook.com/events/195194843902656/",
"non_regular": "y",
"special": "y",
"blurp": "Wow, this is what all hardcore fans have been waiting for, UNDEROATH in Singapore! Don't miss these hardcore legends!",
},
{
"date": "9 Mar 12",
"place": "Esplanade Theatre Studio",
"name": "Mosaic Festival presents: Architecture in Helsinki (AUS)",
"genre": "Indie Pop",
"time": "1930 & 2200",
"price": "$40/$48",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/mc_architectinhelsinki.html",
"non_regular": "y",
"special": "y",
"blurp": "Mosaic Festival presents Architecture in Helsinki with their whimsical indie pop music, sure to make us dance to!",
},
{
"date": "10 Mar 12",
"place": "Esplanade Theatre",
"name": "Mosaic Festival presents: OMD (UK)",
"genre": "Electronica; New Wave; Rock",
"time": "2100",
"price": "TBA",
"website": "http://www.mosaicmusicfestival.com/",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "10 Mar 12",
"place": "Esplanade Theatre Studio",
"name": "Mosaic Festival presents: Craft Spells (USA)",
"genre": "Indie Pop",
"time": "2200",
"price": "$40/$48",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/mc_craftspells.html",
"non_regular": "y",
"special": "y",
"blurp": "Mosaic Festival presents Craft Spells, a indie pop band with their infectuous chill-wave sort of tunes and hypnotising vocals.",
},
{
"date": "10 Mar 12",
"place": "Singapore Indoor Stadium",
"name": "DURAN DURAN Live in Singapore",
"genre": "Hip hop; Rock; Pop; Techno",
"time": "2000",
"price": "$98/$148/$228",
"website": "http://www.sistic.com.sg/portal/dt?dt.isPortletRequest=true&dt.action=process&dt.provider=PortletWindowProcessChannel&dt.windowProvider.targetPortletChannel=JSPTabContainer/sEventsCalendar/Event&dt.containerName=JSPTabContainer/sEventsCalendar&dt.windowProvider.currentChannelMode=VIEW&dt.window.portletAction=RENDER&contentCode=duran0312",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "10 Mar 12",
"place": "The Black Hall",
"name": "The Dillinger Escape Plan",
"genre": "Mathcore; Hardcore",
"time": "1900 - 2200",
"price": "$40/$50/$60",
"website": "http://www.facebook.com/events/202456629835473/",
"non_regular": "y",
"special": "y",
"blurp": "The Dillinger Escape plan creatively incorporates various influences of metal and hardcore to their music and are also known for their intense live performances!",
},
{
"date": "11 Mar 12",
"place": "Esplanade Concert Hall",
"name": "Mosaic Festival presents: Poncho Sanchez And His Latin Jazz Band (USA)",
"genre": "Latin Jazz",
"time": "1930",
"price": "$40/$60/$80, Limited concession for students, NSF and senior citizens: $25*, $40**",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ch_ponchosanchez.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "12 Mar 12",
"place": "TBA",
"name": "A Day to Remember",
"genre": "Hardcore",
"time": "TBA",
"price": "TBA",
"website": "http://www.facebook.com/events/319408088078189/",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "13 Mar 12",
"place": "Esplanade Concert Hall",
"name": "Mosaic Festival presents: Guitarrista de Flamenco Vicente Amigo",
"genre": "Flamenco; Jazz",
"time": "1930",
"price": "$40/$60/$80, Limited concession for students, NSF and senior citizens: $25*, $40**",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ch_guitarrista.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "15 Mar 12",
"place": "Esplanade Concert Hall",
"name": "Mosaic Festival presents: John Butler Trio (AUS)",
"genre": "Alternative Rock",
"time": "1930",
"price": "$40/$60/$80, Limited concession for students, NSF and senior citizens: $25*, $40**",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ch_johnbutler.html",
"non_regular": "y",
"special": "y",
"blurp": "In 1998 singer-songwriter John Butler was busking on the streets of Fremantle. Now, together with his two bandmates, he has become the most successful independent artist in Australia and an international favourite!",
},
{
"date": "15 Mar 12",
"place": "Esplanade Recital Studio",
"name": "Mosaic Festival presents: Tyondai Braxton (USA)",
"genre": "Experimental; Rock",
"time": "1930 & 2130",
"price": "$30, Limited concession for students, NSF and senior citizens: $20*",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ms_tyondaibraxton.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "16 Mar 12",
"place": "Esplanade Concert Hall",
"name": "Mosaic Festival presents: Makoto Ozone featuring No Name Horses (JAP)",
"genre": "Jazz",
"time": "1930",
"price": "$40/$60/$80, Limited concession for students, NSF and senior citizens: $25*, $40**",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ch_makotoozone.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "16 Mar 12",
"place": "Esplanade Recital Studio",
"name": "Mosaic Festival presents: Arctic Accordion with Kimmo Pohjonen (FIN)",
"genre": "Accordion; Experimental",
"time": "1930",
"price": "$30, Limited concession for students, NSF and senior citizens: $20*",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ms_arcticaccordion.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "16 Mar 12",
"place": "Esplanade Theatre Studio",
"name": "Mosaic Festival presents: toe (JAP)",
"genre": "Math Rock; Post-Rock; Instrumental",
"time": "2200",
"price": "$40/$48",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/mc_toe.html",
"non_regular": "y",
"special": "y",
"blurp": "Japanese instrumental rock music group toe plays music with mystical harmonies and raw emotion. Their explosive live performances have left fans across the globe spellbound!",
},
{
"date": "17 Mar 12",
"place": "Esplanade Recital Studio",
"name": "Mosaic Festival presents: Ari Hoenig Quartet (USA)",
"genre": "Jazz",
"time": "1930",
"price": "$30, Limited concession for students, NSF and senior citizens: $20*",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ms_arihoenig.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "17 Mar 12",
"place": "Esplanade Theatre Studio",
"name": "Mosaic Festival presents: Los Campesinos! (UK)",
"genre": "Indie; Pop; Punk",
"time": "1930 & 2200",
"price": "$40/$48",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/mc_loscampesinos.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "18 Mar 12",
"place": "Esplanade Concert Hall",
"name": "Mosaic Festival presents: elbow (UK)",
"genre": "Progressive Rock; Brit-Rock; Indie Rock",
"time": "1930",
"price": "$40/$60/$80, Limited concession for students, NSF and senior citizens: $25*, $40**",
"website": "http://www.mosaicmusicfestival.com/2012/microsite/ch_elbow.html",
"non_regular": "y",
"special": "none",
"blurp": "none",
},
{
"date": "30 Mar 12",
"place": "Esplanade Recital Studio",
"name": "Time Trails",
"genre": "",
"time": "2130",
"price": "$25",
"website": "http://www.esplanade.com/whats_on/programme_info/time_trails/index.jsp",
"non_regular": "none",
"special": "none",
"blurp": "none",
},
{
"date": "12 Apr 12",
"place": "Fort Canning Park",
"name": "Sum 41",
"genre": "Punk Rock",
"time": "TBA",
"price": "TBA",
"website": "",
"non_regular": "y",
"special": "y",
"blurp": "Sum 41 will unleash its rambunctious brand of power punk pop in Singapore again!",
},
]
