places = [
{
"place": "Acid Bar",
"address": "180 Orchard Road, Peranakan Place",
"postal": "238846",
"tel": "6738 8828",
"website": "www.peranakanplace.com/acidbar.html",
"details": "Aptly described as an enclave with edge and soul by grungy barflies and creative cracks. Experience a blend of sensory elements and take flight to a different plane. Acoustic sessions featuring genres of radio alternatives, top 40s and an occasional touch of percussions are played nightly from 7pm.  Consume nightly before rest a myriad of concoctions; tray of 25 apple/lychee shooters and buckets of the golden juice with touch go budgets.  Fret not growling guts as our kitchen maestro whips up tantelicious hot chicken wings and crunchy calamari while acid bar croons and the blue cows dance.",
"latitude": "1.3014626",
"longitude": "103.8391229",
},
{
"place": "Blujaz Cafe",
"address": "11 Bali Lane",
"postal": "189848",
"tel": "6292 3800",
"website": "www.blujaz.net/",
"details": "At BluJaz, we believe in the simple things of life. Simple things that have somehow become so hard to find. Good food. Love. Laughter. Friends. Family. Music. Conversation. And decent prices, because no one should be allowed to pay fifty dollars for a meal.",
"latitude": "1.300639",
"longitude": "103.858993",
},
{
"place": "Brix",
"address": "10 Scotts Rd, Basement, Grand Hyatt Singapore",
"postal": "228211",
"tel": "6732-1234",
"website": "http://singapore.grand.hyatt.com/hyatt/hotels/entertainment/lounges/index.jsp",
"details": "There’s a lively yet sophisticated feel to Brix, buried in the basement of the Grand Hyatt Regency. Despite its subterranean location, it’s not at all dingy, and crowds flock here to enjoy the live music from the popular house band. International bands occasionally perform too. Divided in two, a Music Bar, where the band play a pleasing blend of jazz and R&B, and a Wine & Whiskey Bar, which, good to its name, serves up a fine selection of wine, Scotch, and cognac. It can get quite lively on the weekend, the blend of music, dancing and decent drinks, unsurprisingly proving alluring, so dress to impress to ensure you get in. Reservations are also recommended on busy nights.",
"latitude": "1.2894365",
"longitude": "103.8499802",
},
{
"place": "China One",
"address": "Block 3E River Valley Road #02-01 Clarke Quay",
"postal": "179024",
"tel": "6339 0280",
"website": "www.chinaone.com.sg/",
"details": "Indulge in old world charm and modern decadence at China One. Presented in ornate and luxurious undertones, China One's expansive interiors are adorned with Chinese antique furniture, intricate lantern lighting and plush leather chairs. Move to rousing music brought to you by our live bands every night of the week. Resident DJ Tony To (Amsterdam) will keep the crowds entertained throughout the night with his house mixes. Our stable of pool tables that will impress even the most demanding of players. Touted as Singapore's most divine pool and lounge bar, Baize is set to distinguish itself in a class of its own.",
"latitude": "1.2894365",
"longitude": "103.8499802",
},
{
"place": "Crazy Elephant",
"address": "Clarke Quay, 3E River Valley Road, #01-03/04",
"postal": "179024",
"tel": "6337 7859",
"website": "www.crazyelephant.com/",
"details": "Welcome to Southeast Asia's Premier Blues Bar for the true blue Blues fan. Enter it's timber decor, graffiti and raw stage, and come face to face with live blues and rock & roll the way its meant to be.  Fancy coming onstage and rocking out? Come Sunday to Jam night where anyone can come aboard for a blues rock jam.  Many international rock and blues legends have came in for performances, jam sessions or just to enjoy a casual drink with friends.",
"latitude": "1.2894365",
"longitude": "103.8499802",
},
{
"place": "Esplanade Concert Hall",
"address": "1 Esplanade Drive",
"postal": "38981",
"tel": "8288377",
"website": "www.esplanade.com/",
"details": "Esplanade's crown jewel is its 1,600-seat Concert Hall, which boasts superb acoustics by world-renowned acoustician, the late Russell Johnson of Artec Consultants Inc, USA. Designed with the best acoustics in mind, it hosts a diverse range of music performances.",
"latitude": "1.2903246",
"longitude": "103.8548283",
},
{
"place": "Highlander",
"address": "Block 3B The Foundry #01-11 Clarke Quay River Valley Road",
"postal": "179021",
"tel": "6235 9528",
"website": "www.highlanderasia.com/",
"details": "Whiskies: •  Over 250 whiskies from Scotland and around the world •  By the glass: S$10 onwards •  By the bottle: S$125 onwards Drinks: •  Scottish beers •  Whisky cocktails •  Whisky liqueurs •  House pours, cocktails, mocktails, soft drinks and juices •  Coffees and teas Food: Traditional Scottish fare with a contemporary twist Total seating capacity: 160 Main room: 50 Private room: 28 Seats at the Bar: 10 Alfresco: 72 Entertainment: Live music daily from 9.30pm onwards",
"latitude": "1.2894365",
"longitude": "103.8499802",
},
{
"place": "Hood",
"address": "55 Keong Saik Road",
"postal": "89158",
"tel": "62218846",
"website": "www.hoodbarandcafe.com/",
"details": "Situated in the heart of historical Chinatown, Hood bar and café is the epitome of local charm that brings the best of music, art and culture in Singapore.",
"latitude": "1.28072",
"longitude": "103.84161",
},
{
"place": "Quarubar",
"address": "113 Frankel Ave",
"postal": "458230",
"tel": "6243 0113",
"website": "www.facebook.com/group.php?gid=46581108311",
"details": "Quaruba'r (pronounced: kwa-roo-bar NOT car-roo-bar)  Chill to our draft beer of Stella Artois, Hoegaarden and San Miguel. Catch the latest sports on the TV screens. Savor our concoctions with delectable choice of finger food. Be serenaded by the harmonies of Jazz, Latin & Tango performed by our musicians as our meticulously mixed cocktails tease your palate.  We are open 365 days a year. Sunday to Thursday 4pm to 1am. Friday, Saturday, eve of Public Holiday and Public Holiday 4pm to 2am.  Dress code : Whatever you're comfortable in...seriously",
"latitude": "1.314281",
"longitude": "103.919472",
},
{
"place": "Timbre Arts House",
"address": "1 Old Parliament Lane",
"postal": "179429",
"tel": "6332 6900",
"website": "www.timbre.com.sg/",
"details": "Music serenity by the river",
"latitude": "1.288651",
"longitude": "103.851078",
},
{
"place": "Timbre Old School",
"address": "11A Mount Sophia",
"postal": "179936",
"tel": "6338 8277",
"website": "www.timbre.com.sg/",
"details": "Offers a solitude and respite high above the maddening busy city.",
"latitude": "1.300699",
"longitude": "103.847405",
},
{
"place": "Timbre Substation",
"address": "45 Armenian Street",
"postal": "179936",
"tel": "6338 8277",
"website": "www.timbre.com.sg/",
"details": "Music oasis in the city",
"latitude": "",
"longitude": "1.29452",
},
{
"place": "Wala Wala",
"address": "31 Lorong Mambong Holland Village",
"postal": "277689",
"tel": "64624288",
"website": "www.imaginings.com.sg/",
"details": "Set in Holland Village, a part of Singapore that could be a chic version of Cheltenham, well-to-do locals and ex-pats come to chill out in a lively downstairs bar serving beer, wine and Singapore Slings, and then head upstairs for live music and tail-shaking.",
"latitude": "1.311636",
"longitude": "103.79569",
},
{
"place": "Yello Jello Retrobar",
"address": "Clarke Quay, Blk 3C The Cannery, River Valley Rd, #01-06",
"postal": "179021",
"tel": "6887 3733",
"website": "www.yellojello.sg/",
"details": "Yello Jello officially re-brands with a new look and revision in music policy, spotting more rockish anthems from the 80s, 90s and some of today’s pop rock favourites.",
"latitude": "1.2894365",
"longitude": "103.8499802",
},
{
"place": "Wave House Sentosa",
"address": "36 Siloso Beach Walk",
"postal": "99007",
"tel": "6377 3113",
"website": "http://wavehousesentosa.com/",
"details": "Wave House Sentosa is the fourth and newest installation in an archipelago of Wave Houses that stretches from Durban in South Africa, San Diego in California, to Santiago in Chile. This latest addition to the Wave House chain is loated on the sandy beaches of Sentosa, a small island off the Singapore mainland, the southern most tip of the Asian Continent.",
"latitude": "none",
"longitude": "none",
},
]
