/* App Controllers */

function EventsCatCtrl($route) {
var self = this;

$route.when('/events', {template: 'partials/events-list.html', controller: EventsListCtrl});
$route.when('/place/:place', {template: 'partials/place-detail.html'});
$route.when('/artiste/:artiste', {template: 'partials/artiste-detail.html', controller: EventsListCtrl});
$route.otherwise({redirectTo: '/events'});

$route.onChange(function(){
self.params = $route.current.params;
});

$route.parent(this);
}

//EventsCatCtrl.$inject = ['$route'];

function EventsListCtrl() {
	  var self = this;
	    this.events =
		[
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Acid Bar",
		"artiste": "Nelson",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Acid Bar",
		"artiste": "Tuna Pop",
		"genre": "Acoustic",
		"time": "2130-0045",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Blujaz Cafe",
		"artiste": "Greg Lyons and 10 piece band, Omniform",
		"genre": "Jazz",
		"time": "2130",
		"price": "$$ (Free entry)",
		"description": "What started off as a chance to play Greg’s arrangements has evolved to include all the individual characters that form the band. The repertoire is still made up largely of Greg’s compositions and wholly of his arrangements which draw from just about every genre of music. Omniform also features some awesome and very individual soloists. Monster Trio, sometimes a quartet consists of talented musicians.",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "China One",
		"artiste": "Tonelab",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Esplanade Concert Hall",
		"artiste": "The 50s Rock & Roll",
		"genre": "Rock",
		"time": "1030; 1500",
		"price": "$10-12",
		"description": "Enjoy and rock to the music of the 50s including Johnny Be Good, Rock Around the Clock, Great Balls of Fire, Hound Dog, La Bamba and more, performed by home grown band Jerry N The Neu Faces!",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Hood",
		"artiste": "Wanyue",
		"genre": "Pop",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Quarubar",
		"artiste": "Dawn Ho & Munir Alsagoff",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Timbre Arts House",
		"artiste": "Surath & Rene",
		"genre": "Jazz",
		"time": "2030-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Timbre Old School",
		"artiste": "Pam & Chris",
		"genre": "Jazz",
		"time": "1945-2300",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Timbre Substation",
		"artiste": "Michaela Therese",
		"genre": "Jazz",
		"time": "2215-0030",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Wala Wala",
		"artiste": "Three",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/4/2011",
		"day": "Monday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Acid Bar",
		"artiste": "Joshua Alexis",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Acid Bar",
		"artiste": "Kulture",
		"genre": "Acoustic",
		"time": "2130-0045",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "Free (excl F&B)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "China One",
		"artiste": "Lydia Low and DJ Tovan",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Hood",
		"artiste": "Singapore Char Siew Bao",
		"genre": "",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Quarubar",
		"artiste": "Dawn Ho & Munir Alsagoff",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Timbre Arts House",
		"artiste": "53A",
		"genre": "Rock",
		"time": "2015-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Timbre Old School",
		"artiste": "Fatt, Shili & Adi",
		"genre": "Rock",
		"time": "1945-2300",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Timbre Substation",
		"artiste": "Goodfellas",
		"genre": "Rock",
		"time": "2115-0030",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Wala Wala",
		"artiste": "Hush",
		"genre": "Pop Rock",
		"time": "1900",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Wala Wala",
		"artiste": "Tabula",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/5/2011",
		"day": "Tuesday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Acid Bar",
		"artiste": "Jamiel",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Acid Bar",
		"artiste": "Pam & Fatt",
		"genre": "Acoustic",
		"time": "2130-0045",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "China One",
		"artiste": "Inertia (Acoustic) & DJ Tovan",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Hood",
		"artiste": "Shimona",
		"genre": "",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Quarubar",
		"artiste": "Lily Nuris & Wayne Sandz",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Timbre Arts House",
		"artiste": "Enigma",
		"genre": "Rock",
		"time": "2015-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Timbre Old School",
		"artiste": "Liza & Joey",
		"genre": "Rock",
		"time": "1945-2300",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Timbre Substation",
		"artiste": "Raw Earth",
		"genre": "Rock",
		"time": "2115-0030",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Wala Wala",
		"artiste": "Ngak",
		"genre": "Pop Rock",
		"time": "1900",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Wala Wala",
		"artiste": "Timmy",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/6/2011",
		"day": "Wednesday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Acid Bar",
		"artiste": "Nelson",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Acid Bar",
		"artiste": "Tuna Pop",
		"genre": "Acoustic",
		"time": "2130-0045",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "China One",
		"artiste": "Tabula (Acoustic) & DJ Tovan",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Hood",
		"artiste": "Howie + Nelson",
		"genre": "",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Quarubar",
		"artiste": "Wayne Sandz & Joe",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Timbre Arts House",
		"artiste": "Iris Feat. Liza",
		"genre": "Rock",
		"time": "2015-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Timbre Old School",
		"artiste": "53A",
		"genre": "Rock",
		"time": "2015-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Timbre Substation",
		"artiste": "Goodfellas",
		"genre": "Rock",
		"time": "2215-0045",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Wala Wala",
		"artiste": "Victor Tang",
		"genre": "Pop Rock",
		"time": "1900",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Wala Wala",
		"artiste": "The Unexpected",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/7/2011",
		"day": "Thursday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Acid Bar",
		"artiste": "Matt",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Acid Bar",
		"artiste": "Sofia & Fatt",
		"genre": "Acoustic",
		"time": "2130-0015",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Acid Bar",
		"artiste": "Sugarlove",
		"genre": "Acoustic",
		"time": "0030-0215",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "China One",
		"artiste": "Tabula (Full Band) and DJ Tovan",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Esplanade Concert Hall",
		"artiste": "Presidents Young Performers Concert",
		"genre": "Classical",
		"time": "1930",
		"price": "$15+ , $22+ , $32+ , $42, $58, $72 Concessions: Concessions for students, NSF and senior citizens: 30% savings",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Hood",
		"artiste": "Timmy! Band",
		"genre": "",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Quarubar",
		"artiste": "Carlos",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Timbre Arts House",
		"artiste": "Goodfellas",
		"genre": "Pop",
		"time": "2130-1245",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Timbre Old School",
		"artiste": "Alicia Pan & Adrian",
		"genre": "Pop",
		"time": "2015-2330",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Timbre Substation",
		"artiste": "53A",
		"genre": "Pop",
		"time": "2230-0145",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Wala Wala",
		"artiste": "53A",
		"genre": "Pop Rock",
		"time": "1900",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Wala Wala",
		"artiste": "The Common People",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/8/2011",
		"day": "Friday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Acid Bar",
		"artiste": "Faisal",
		"genre": "Acoustic",
		"time": "1900-2100",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Acid Bar",
		"artiste": "Kulture",
		"genre": "Acoustic",
		"time": "2130-0015",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Acid Bar",
		"artiste": "Sugarlove",
		"genre": "Acoustic",
		"time": "0030-0215",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Blujaz Cafe",
		"artiste": "Ayaschool",
		"genre": "Jazz",
		"time": "2130",
		"price": "$$ (Free entry)",
		"description": "Ayaschool visits Blu Jaz Cafe on Saturdays where Aya Sekine brings friends like DJ KoFlow, Alemay Fernandez, Angelita Li, Fendi, Budi to the mic. And by her second set, she brings down the house with her incredible improvisation and energy.",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Brix",
		"artiste": "Shades",
		"genre": "R&B; Soul; Calypso",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "China One",
		"artiste": "Tabula (Full Band) and DJ Tovan",
		"genre": "",
		"time": "2100",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Crazy Elephant",
		"artiste": "Crazy Elephant Band",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Esplanade Concert Hall",
		"artiste": "Colours of the Wind东西双笛韵",
		"genre": "Classical; Chinese",
		"time": "1930",
		"price": "$25+ , $35+ + , $55, $75, $95 Concessions: Limited concessions for students, NSF & senior citizens: $14+  / $19+ + ",
		"description": "A dialogue between recorder and dizi 西洋竖笛和中国竹笛的对话 Co-produced by Esplanade – Theatres on the Bay and Singapore Chinese Orchestra. 由新加坡华乐团呈献，与滨海艺术中心联合制作",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Highlander",
		"artiste": "Dejavu",
		"genre": "Acoustic",
		"time": "2130",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Hood",
		"artiste": "Pennylane Band",
		"genre": "",
		"time": "",
		"price": "Free (excl F&B)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Quarubar",
		"artiste": "Alemay & Shawn Letts",
		"genre": "Jazz; Latin; Tango",
		"time": "",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Timbre Arts House",
		"artiste": "Iris Feat. Liza",
		"genre": "Rock",
		"time": "2130-1245",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Timbre Old School",
		"artiste": "Sofia & Fatt",
		"genre": "Rock",
		"time": "2115-1230",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Timbre Substation",
		"artiste": "Goodfellas",
		"genre": "Rock",
		"time": "2230-0145",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Wala Wala",
		"artiste": "The Unexpected",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "Free (excl F&B)",
		"description": "none",
		},
		{
		"date": "7/9/2011",
		"day": "Saturday",
		"place": "Yello Jello Retrobar",
		"artiste": "",
		"genre": "",
		"time": "",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Acid Bar",
		"artiste": "Sugarlove",
		"genre": "Acoustic",
		"time": "2100-0030",
		"price": "$$$ + $20 cover",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Crazy Elephant",
		"artiste": "Jam Session",
		"genre": "Blues",
		"time": "2200",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Esplanade Concert Hall",
		"artiste": "Sparks Goes POP! Sparks流行风!",
		"genre": "Classical; Chinese",
		"time": "1500",
		"price": "Free",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Esplanade Recital Studio",
		"artiste": "The Tryst",
		"genre": "",
		"time": "1930",
		"price": "$24Concessions: for students, NSF and senior citizens: $16",
		"description": "Intimate encounters with four late 20th century composers at the disco, in a garden and on the road, all after violin and piano have taken a Scottish love poem and weaved their own tender embraces around it. Dutch composer Louis Andriessen says of his modern take on the dance hall, \"Nothing goes smoothly any more\", while, in characteristically mystic and misty vein, Japan's greatest 20th century composer declares \"I would like to achieve a sound as intense as silence\". For his part, John Adams describes his 1995 piece for violin and piano as beginning with \"a relaxed drive down a not unfamiliar road\" and ending with \"a giddy, bouncy ride for four wheel drives only\". It all sounds pretty frenetic but, again to quote Adams, \"Relax, and let us do the driving!\"",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Hood",
		"artiste": "Victor Tang",
		"genre": "",
		"time": "",
		"price": "$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "The Pump Room",
		"artiste": "Jive Talkin'",
		"genre": "Pop, Rock, Jazz",
		"time": "2245",
		"price": "$$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Timbre Substation",
		"artiste": "Timbre Academy All Stars",
		"genre": "Pop",
		"time": "2145-0030",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Wala Wala",
		"artiste": "Jack & Rai",
		"genre": "Pop Rock",
		"time": "Prime Time",
		"price": "$$ (Free entry)",
		"description": "none",
		},
		{
		"date": "7/10/2011",
		"day": "Sunday",
		"place": "Yello Jello Retrobar",
		"artiste": "John Molina & Krueger",
		"genre": "Rock",
		"time": "2200",
		"price": "$$ (Free entry)",
		"description": "none",
		}
		] }

function PlacesDetailCtrl() {
	var self = this;
	this.places =
	[
	{
	"place": "Acid Bar",
	"address": "180 Orchard Road, Peranakan Place",
	"postal": "238846",
	"tel": "6738 8828",
	"details": "Aptly described as an enclave with edge and soul by grungy barflies and creative cracks. Experience a blend of sensory elements and take flight to a different plane. Acoustic sessions featuring genres of radio alternatives, top 40s and an occasional touch of percussions are played nightly from 7pm.  Consume nightly before rest a myriad of concoctions; tray of 25 apple/lychee shooters and buckets of the golden juice with touch go budgets.  Fret not growling guts as our kitchen maestro whips up tantelicious hot chicken wings and crunchy calamari while acid bar croons and the blue cows dance.",
	},
	{
	"place": "Blujaz Cafe",
	"address": "11 Bali Lane",
	"postal": "189848",
	"tel": "6292 3800",
	"details": "At BluJaz, we believe in the simple things of life. Simple things that have somehow become so hard to find. Good food. Love. Laughter. Friends. Family. Music. Conversation. And decent prices, because no one should be allowed to pay fifty dollars for a meal.",
	},
	{
	"place": "Brix",
	"address": "10 Scotts Rd, Basement, Grand Hyatt Singapore",
	"postal": "228211",
	"tel": "6732-1234",
	"details": "There’s a lively yet sophisticated feel to Brix, buried in the basement of the Grand Hyatt Regency. Despite its subterranean location, it’s not at all dingy, and crowds flock here to enjoy the live music from the popular house band. International bands occasionally perform too. Divided in two, a Music Bar, where the band play a pleasing blend of jazz and R&B, and a Wine & Whiskey Bar, which, good to its name, serves up a fine selection of wine, Scotch, and cognac. It can get quite lively on the weekend, the blend of music, dancing and decent drinks, unsurprisingly proving alluring, so dress to impress to ensure you get in. Reservations are also recommended on busy nights.",
	},
	{
	"place": "China One",
	"address": "Block 3E River Valley Road #02-01 Clarke Quay",
	"postal": "179024",
	"tel": "6339 0280",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Crazy Elephant",
	"address": "Clarke Quay, 3E River Valley Road, #01-03/04",
	"postal": "179024",
	"tel": "6337 7859",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Esplanade Concert Hall",
	"address": "1 Esplanade Drive",
	"postal": "38981",
	"tel": "8288377",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Highlander",
	"address": "Block 3B The Foundry #01-11 Clarke Quay River Valley Road",
	"postal": "179021",
	"tel": "6235 9528",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Hood",
	"address": "55 Keong Saik Road",
	"postal": "89158",
	"tel": "62218846",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Quarubar",
	"address": "113 Frankel Ave",
	"postal": "458230",
	"tel": "6243 0113",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Timbre Arts House",
	"address": "1 Old Parliament Lane",
	"postal": "179429",
	"tel": "6332 6900",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Timbre Old School",
	"address": "11A Mount Sophia",
	"postal": "179936",
	"tel": "6338 8277",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Timbre Substation",
	"address": "45 Armenian Street",
	"postal": "179936",
	"tel": "6338 8277",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Wala Wala",
	"address": "31 Lorong Mambong Holland Village",
	"postal": "277689",
	"tel": "64624288",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	{
	"place": "Yello Jello Retrobar",
	"address": "Clarke Quay, Blk 3C The Cannery, River Valley Rd, #01-06",
	"postal": "179021",
	"tel": "6887 3733",
	"details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit ante in arcu consequat vel mollis nisi auctor. Aenean convallis, erat nec ultrices gravida, diam ligula pellentesque mauris, eget hendrerit lorem mauris at turpis. Suspendisse fringilla egestas augue vel varius. Etiam lorem est, viverra vel convallis in, volutpat sed risus. Sed ac orci tortor, sed euismod neque. Mauris nibh libero, varius in molestie at, accumsan ullamcorper mauris. Ut eu urna nec mauris volutpat suscipit et ac dui.",
	},
	] }

